#!/usr/bin/env python3
"""The same discipline as check_docs.py, one directory down.

`check_docs.py` guards the Arabic notes of the earlier papers and
`paper/check_paper.py` guards the manuscript. The contemporary notes had no
guard, and they are now the documents most likely to drift: they carry the
decomposition, the article-level seams and the profile, all of which are read
from result files that get re-run.

Every headline figure in these notes is declared here with the result file
and key it comes from, and checked as it is written in the prose. The script
does not rewrite prose -- a number in a sentence usually needs the sentence
changed too -- it says which figure moved and where.

    python3 check_notes.py
"""
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
J = lambda n: json.loads((HERE / n).read_text(encoding="utf-8"))


def facts():
    ov, hy = J("overlap_results.json"), J("hybrid_results.json")
    ret, cf = J("retrieval_results.json"), J("core_function.json")
    fg, pg = J("function_gold.json"), J("pairs_gold.json")
    hg = J("hybrid_gold.json")
    cp, cd = J("completeness_results.json"), J("codes_results.json")
    si, ap = J("silence_results.json"), J("appellate_results.json")
    rg, hr = J("rag_gap_results.json"), J("hybrid_roles_gold.json")
    tl, ec = J("twolayers_results.json"), J("ecology_results.json")
    tr, af = J("traceability_results.json"), J("adjudicative_function_gold.json")
    ins, ief = J("instruments_results.json"), J("instrument_effect_results.json")
    ai = J("article_instrument_results.json")
    cm = J("companion_analysis_results.json")
    fo, aib = J("foresight_results.json"), J("ai_baseline_results.json")
    fl = J("FORECAST_LEDGER.json")
    reg, rad = J("adoption_registry.json"), J("ai_radar_results.json")
    b2, amap = J("ai_baseline_v2_results.json"), J("ai_transition_map.json")
    xm, bau = J("ai_exposure_matrix_results.json"), J("bog_access_audit.json")
    hz, dt = J("horizon_results.json"), J("detectors_results.json")
    dk = J("docket_test_results.json")
    lg, dm = J("locality_gold.json"), J("docket_model_results.json")
    S, C = ov["specs"]["strict"], ov["conditional"]["strict"]
    W = ov["conditional"]["wide"]
    y, seam = hy["years"], hy["seams"]
    art = {(r["instrument"], r["article"]): r for r in seam["articles"]}
    out = [
        ("art_all no-overlap", f"{S['art_all']['noOverlapPct']}",
         ["DECOMPOSITION.md", "contemporary_commercial_adjudication_profile.md"]),
        ("art_nostruct no-overlap", f"{S['art_nostruct']['noOverlapPct']}",
         ["DECOMPOSITION.md", "BACKLOG.md"]),
        ("art_dispute no-overlap", f"{S['art_dispute']['noOverlapPct']}",
         ["DECOMPOSITION.md", "BACKLOG.md"]),
        ("P(shared instrument)", f"{C['sharedInstrumentPct']}",
         ["DECOMPOSITION.md", "BACKLOG.md"]),
        ("P(shared article | instrument)",
         f"{C['sharedArticleGivenInstrumentPct']}",
         ["DECOMPOSITION.md", "BACKLOG.md"]),
        ("P(shared article | instrument), wide",
         f"{W['sharedArticleGivenInstrumentPct']}", ["DECOMPOSITION.md"]),
        ("Spearman court/party", f"{ret['spearman']['court_vs_party']}",
         ["DECOMPOSITION.md",
          "contemporary_commercial_adjudication_profile.md"]),
        ("top-50 structural share",
         f"{cf['contemporary_3y_top50']['class']['STRUCTURAL_PROCEDURAL']}",
         ["DECOMPOSITION.md",
          "contemporary_commercial_adjudication_profile.md"]),
        ("top-10 structural share",
         f"{cf['contemporary_3y_top10']['class']['STRUCTURAL_PROCEDURAL']}",
         ["DECOMPOSITION.md"]),
        ("fiqh prevalence 1444",
         f"{y['1444']['authority']['fiqh_source']['prevalencePct']}",
         ["NEXT_PROGRAMME.md", "CONTEMPORARY_MAP.md"]),
        ("fiqh prevalence 1446",
         f"{y['1446']['authority']['fiqh_source']['prevalencePct']}",
         ["NEXT_PROGRAMME.md", "CONTEMPORARY_MAP.md"]),
        ("fiqh intensity 1446",
         f"{y['1446']['authority']['fiqh_source']['intensity']}",
         ["NEXT_PROGRAMME.md", "CONTEMPORARY_MAP.md"]),
        ("statute prevalence 1446",
         f"{y['1446']['authority']['statute']['prevalencePct']}",
         ["NEXT_PROGRAMME.md", "CONTEMPORARY_MAP.md"]),
        ("statute intensity 1446",
         f"{y['1446']['authority']['statute']['intensity']}",
         ["NEXT_PROGRAMME.md", "CONTEMPORARY_MAP.md"]),
        ("seam base rate", f"{seam['basePct']}", ["NEXT_PROGRAMME.md"]),
        ("CCL 29 seam rate",
         f"{art[('commercial_courts_law', 29)]['nonStatutePct']}",
         ["NEXT_PROGRAMME.md", "DECOMPOSITION.md"]),
        ("CCL-IR 164 seam rate",
         f"{art[('commercial_courts_implementing_regulation', 164)]['nonStatutePct']}",
         ["NEXT_PROGRAMME.md"]),
        ("CCL-IR 58 seam rate",
         f"{art[('commercial_courts_implementing_regulation', 58)]['nonStatutePct']}",
         ["NEXT_PROGRAMME.md", "DECOMPOSITION.md"]),
        ("Evidence 3 seam rate",
         f"{art[('evidence_law', 3)]['nonStatutePct']}", ["NEXT_PROGRAMME.md"]),
        ("seam rate, structural class",
         f"{seam['byClass']['STRUCTURAL_PROCEDURAL']['nonStatutePct']}",
         ["NEXT_PROGRAMME.md"]),
        ("seam rate, dispute class",
         f"{seam['byClass']['DISPUTE_SPECIFIC']['nonStatutePct']}",
         ["NEXT_PROGRAMME.md"]),
        ("structural precision, gold",
         f"{fg['labels']['structuralPrecision']['correct']} of "
         f"{fg['labels']['structuralPrecision']['n']}", []),
        ("pairs answered on other law",
         f"{pg['labels']['counts']['ANSWERED_ON_OTHER_LAW']}", []),
        ("hybrid sample ornament count",
         f"{hg['counts']['ORNAMENT']}", []),
        # --- the completeness programme
        ("open-textured pooled",
         f"{cp['byClass']['OPEN_TEXTURED_STANDARD']['judgmentLevelPct']}",
         ["COMPLETENESS.md"]),
        ("open-textured median",
         f"{cp['byClass']['OPEN_TEXTURED_STANDARD']['articleMedianPct']}",
         ["COMPLETENESS.md"]),
        ("institutional median",
         f"{cp['byClass']['INSTITUTIONAL_DIRECTIVE']['articleMedianPct']}",
         ["COMPLETENESS.md"]),
        ("institutional median, unseen",
         f"{cp['byClassUnseenOnly']['INSTITUTIONAL_DIRECTIVE']['articleMedianPct']}",
         ["COMPLETENESS.md"]),
        ("external referral pooled, unseen",
         f"{cp['byClassUnseenOnly']['EXTERNAL_REFERRAL']['judgmentLevelPct']}",
         ["COMPLETENESS.md"]),
        ("matched pairs median delta",
         f"{cp['matchedPairs']['medianDeltaPts']}", ["COMPLETENESS.md"]),
        ("matched pairs sign test",
         f"{cp['matchedPairs']['signTestP']}", ["COMPLETENESS.md"]),
        ("judicial principle, open-textured",
         f"{cp['byClassByAuthority']['OPEN_TEXTURED_STANDARD']['judicial_principle']}",
         ["COMPLETENESS.md"]),
        ("judicial principle, institutional",
         f"{cp['byClassByAuthority']['INSTITUTIONAL_DIRECTIVE']['judicial_principle']}",
         ["COMPLETENESS.md"]),
        ("bench-bar delta, institutional, strict",
         f"{cp['benchVsBar_party']['byClass']['INSTITUTIONAL_DIRECTIVE']}",
         ["COMPLETENESS.md"]),
        ("CTL pooled non-statutory",
         f"{cd['civilTransactionsLaw']['pooledNonStatutePct']}",
         ["COMPLETENESS.md"]),
        ("Evidence pooled non-statutory",
         f"{cd['evidenceLaw']['pooledNonStatutePct']}", ["COMPLETENESS.md"]),
        ("fiqh per statutory citation 1446",
         f"{cd['denominators']['1446']['fiqhPerStatutoryCitation']}",
         ["COMPLETENESS.md"]),
        ("fiqh per 1k reasoned 1446",
         f"{cd['denominators']['1446']['fiqhCitationsPer1000Reasoned']}",
         ["COMPLETENESS.md"]),
        ("silent share", f"{si['silentPct']}", ["COMPLETENESS.md"]),
        ("silent median reason chars",
         f"{si['silent']['medianReasonChars']:,}", ["COMPLETENESS.md"]),
        ("silence in the shortest decile",
         f"{si['byLengthDecile'][0]['silentPct']}", ["COMPLETENESS.md"]),
        ("paired appellate share", f"{ap['pairedShare']}", ["COMPLETENESS.md"]),
        ("disturbed, non-statute only",
         f"{ap['byShape']['nonstatute_only']['disturbedPct']}",
         ["COMPLETENESS.md"]),
        ("statute-only retrieval omission",
         f"{rg['estimateReasonedJudgmentsWhereStatuteOnlyRetrievalOmitsPct']}",
         ["COMPLETENESS.md"]),
        ("named fiqh with a source",
         f"{rg['namedFiqhWithASourcePct']}", ["COMPLETENESS.md"]),
        ("deletable share of codeable",
         f"{hr['deletionTest']['deletablePctOfCodeable']}",
         ["COMPLETENESS.md"]),
        ("supplies the decision rule",
         f"{hr['counts']['SUPPLIES_THE_DECISION_RULE']}", ["COMPLETENESS.md"]),
        # --- the two-layer programme
        ("rule-label agreement",
         f"{af['agreementWithRuleLabels']['pctWhereRuleDecisive']}",
         ["TWO_LAYERS.md"]),
        ("institutional median",
         f"{tl['byClass']['INSTITUTIONAL_OPERATION']['medianPct']}",
         ["TWO_LAYERS.md"]),
        ("dispute median",
         f"{tl['byClass']['DISPUTE_DECISION']['medianPct']}",
         ["TWO_LAYERS.md"]),
        ("mixed pooled", f"{tl['byClass']['MIXED']['pooledPct']}",
         ["TWO_LAYERS.md"]),
        ("institutional median, rule labels",
         f"{tl['byClassRuleLabels']['INSTITUTIONAL_OPERATION']['medianPct']}",
         ["TWO_LAYERS.md"]),
        ("core top10 institutional",
         f"{tl['coreAnatomy']['top10']['INSTITUTIONAL_OPERATION']}",
         ["TWO_LAYERS.md"]),
        ("core top100 institutional",
         f"{tl['coreAnatomy']['top100']['INSTITUTIONAL_OPERATION']}",
         ["TWO_LAYERS.md"]),
        ("core top100 jurisdiction subtype",
         f"{tl['coreAnatomy']['top100']['institutionalSubtypesPctOfAll']['jurisdiction']}",
         ["TWO_LAYERS.md"]),
        ("court dispute share",
         f"{tl['courtVsParty']['court']['DISPUTE_DECISION']}",
         ["TWO_LAYERS.md"]),
        ("party strict institutional share",
         f"{tl['courtVsParty']['party']['INSTITUTIONAL_OPERATION']}",
         ["TWO_LAYERS.md"]),
        ("eta2, procedural/substantive",
         f"{tl['explanatoryPower']['A_procedural_substantive']['etaSquared']}",
         ["TWO_LAYERS.md"]),
        ("eta2, institutional/dispute",
         f"{tl['explanatoryPower']['C_institutional_dispute']['etaSquared']}",
         ["TWO_LAYERS.md"]),
        ("eta2, instrument identity",
         f"{tl['explanatoryPower']['D_instrument']['etaSquared']}",
         ["TWO_LAYERS.md"]),
        ("hold-out MAE, instrument",
         f"{tl['explanatoryPower']['D_instrument']['holdoutMAE']}",
         ["TWO_LAYERS.md"]),
        ("arbitration hybrid rate",
         f"{ec['profiles']['arbitration_law']['hybridPct']}",
         ["TWO_LAYERS.md"]),
        ("law practice hybrid rate",
         f"{ec['profiles']['law_practice_law']['hybridPct']}",
         ["TWO_LAYERS.md"]),
        ("CTL maxim rate",
         f"{ec['profiles']['civil_transactions_law']['maxim']}",
         ["TWO_LAYERS.md"]),
        ("CCIR named fiqh rate",
         f"{ec['profiles']['commercial_courts_implementing_regulation']['named_fiqh']}",
         ["TWO_LAYERS.md"]),
        # --- traceability and retrieval
        ("statute book full coverage",
         f"{tr['retrievalUniverses']['A_statute_book']['judgmentsFullyCoveredPct']}",
         ["TRACEABILITY.md"]),
        ("whole-judgment precision",
         f"{tr['retrievalUniverses']['B_whole_judgments']['precisionPct']}",
         ["TRACEABILITY.md"]),
        ("unnamed share of court authority",
         f"{tr['overall']['UNNAMED']}", ["TRACEABILITY.md"]),
        ("named source share",
         f"{tr['overall']['NAMED_SOURCE']}", ["TRACEABILITY.md"]),
        ("fiqh unnamed share",
         f"{tr['byAuthorityType']['fiqh_source']['UNNAMED']}",
         ["TRACEABILITY.md"]),
        ("fully traceable judgments",
         f"{tr['perJudgment']['fullyTraceablePct']}", ["TRACEABILITY.md"]),
        # --- the code-ecology programme
        ("arbitration hybrid", f"{ins['ecology']['arbitration_law']['hybridPct']}",
         ["ECOLOGIES.md"]),
        ("law practice hybrid",
         f"{ins['ecology']['law_practice_law']['hybridPct']}", ["ECOLOGIES.md"]),
        ("law practice concentration",
         f"{ins['ecology']['law_practice_law']['top10ConcentrationPct']}",
         ["ECOLOGIES.md"]),
        ("largest profile distance",
         f"{max(ins['profileDistance'].values())}", ["ECOLOGIES.md"]),
        ("between-instrument variance",
         f"{ins['varianceDecomposition']['byInstrument']['betweenSharePct']}",
         ["ECOLOGIES.md"]),
        ("within-instrument variance",
         f"{ins['varianceDecomposition']['byInstrument']['withinSharePct']}",
         ["ECOLOGIES.md"]),
        ("arbitration article sd",
         f"{ins['varianceDecomposition']['perInstrument']['arbitration_law']['sdPct']}",
         ["ECOLOGIES.md"]),
        ("arbitration standardised",
         f"{ief['stratified']['byInstrument']['arbitration_law']['standardisedPct']}",
         ["ECOLOGIES.md"]),
        ("CCL+arbitration both",
         f"{ief['coCitation']['pairs']['commercial_courts_law | arbitration_law']['bothPct']}",
         ["ECOLOGIES.md"]),
        ("SPL+law practice both",
         f"{ief['coCitation']['pairs']['sharia_procedure_law | law_practice_law']['bothPct']}",
         ["ECOLOGIES.md"]),
        ("arbitration marginal within CCL",
         f"{ief['marginalEffect']['byInstrument']['arbitration_law']['withinCCL_marginalPts']}",
         ["ECOLOGIES.md"]),
        ("leave-one-out MAE",
         f"{ief['leaveOneInstrumentOut']['meanAbsoluteErrorPts']}",
         ["ECOLOGIES.md"]),
        ("leave-one-out null",
         f"{ief['leaveOneInstrumentOut']['nullMeanAbsoluteErrorPts']}",
         ["ECOLOGIES.md"]),
        ("arbitration named-source share",
         f"{ins['ecology']['arbitration_law']['supplementaryNamedSourcePct']}",
         ["ECOLOGIES.md"]),
        ("evidence 1446 hybrid",
         f"{ins['stability']['evidence_law']['1446']['hybridPct']}",
         ["ECOLOGIES.md"]),
        ("CTL party strict hybrid",
         f"{ins['voices']['civil_transactions_law']['party_strict']['hybridPct']}",
         ["ECOLOGIES.md"]),
        ("CTL party wide named fiqh",
         f"{ins['voices']['civil_transactions_law']['party_wide']['named_fiqh']}",
         ["ECOLOGIES.md"]),
        # --- the article-level test of the instrument effect
        ("instrument variance share",
         f"{ai['varianceRanking']['instrument']['betweenSharePct']}",
         ["ECOLOGIES.md"]),
        ("instrument excess over chance",
         f"{ai['varianceRanking']['instrument']['excessPts']}",
         ["ECOLOGIES.md", "CLAIM_ECOLOGIES.md"]),
        ("instrument chance share",
         f"{ai['varianceRanking']['instrument']['chanceSharePct']}",
         ["ECOLOGIES.md"]),
        ("article scheme chance share",
         f"{ai['sequential']['chanceShares']['articleProperties']}",
         ["ECOLOGIES.md"]),
        ("article scheme share",
         f"{ai['sequential']['articlePropertiesFirst']['articleShare']}",
         ["ECOLOGIES.md"]),
        ("instrument added to residual",
         f"{ai['sequential']['articlePropertiesFirst']['instrumentShareOfResidual']}",
         ["ECOLOGIES.md", "CLAIM_ECOLOGIES.md"]),
        ("cross-code matched gap",
         f"{ai['functionMatchedPairs']['crossCodeMedianGapPts']}",
         ["ECOLOGIES.md", "CLAIM_ECOLOGIES.md"]),
        ("same-code matched gap",
         f"{ai['functionMatchedPairs']['sameCodeMedianGapPts']}",
         ["ECOLOGIES.md", "CLAIM_ECOLOGIES.md"]),
        ("dispute-deciding same-code gap",
         f"{ai['functionMatchedPairs']['byFunction']['DISPUTE_DECISION']['sameCodeMedianGapPts']}",
         ["ECOLOGIES.md", "CLAIM_ECOLOGIES.md"]),
        ("year share of article-year cells",
         f"{ai['varianceRanking']['year (article-year cells)']['betweenSharePct']}",
         ["ECOLOGIES.md"]),
        ("instrument share of article-year cells",
         f"{ai['varianceRanking']['instrument (same article-year cells)']['betweenSharePct']}",
         ["ECOLOGIES.md"]),
        # --- the docket test
        ("arbitration plea construct lift",
         f"{dk['validity']['arbitrationPlea']['constructLiftPts']}",
         ["DOCKET.md"]),
        ("CCIR standardised",
         f"{dk['standardised']['byInstrument']['commercial_courts_implementing_regulation']['standardisedPct']}",
         ["DOCKET.md", "THEORY_LOG.md"]),
        ("CCIR standardisation delta",
         f"{dk['standardised']['byInstrument']['commercial_courts_implementing_regulation']['deltaPts']}",
         ["DOCKET.md"]),
        ("evidence standardised",
         f"{dk['standardised']['byInstrument']['evidence_law']['standardisedPct']}",
         ["DOCKET.md", "THEORY_LOG.md"]),
        ("arbitration standardised, docket",
         f"{dk['standardised']['byInstrument']['arbitration_law']['standardisedPct']}",
         ["DOCKET.md"]),
        ("bankruptcy strata coverage",
         f"{dk['standardised']['byInstrument']['bankruptcy_law']['strataCoveragePct']}",
         ["DOCKET.md"]),
        ("evidence local w500",
         f"{dk['locality']['w500']['byCode']['evidence_law']['localCoAuthorityPct']}",
         ["DOCKET.md"]),
        ("law practice local w500",
         f"{dk['locality']['w500']['byCode']['law_practice_law']['localCoAuthorityPct']}",
         ["DOCKET.md", "THEORY_LOG.md", "CLAIM_ECOLOGIES.md"]),
        ("CCL local w500",
         f"{dk['locality']['w500']['byCode']['commercial_courts_law']['localCoAuthorityPct']}",
         ["DOCKET.md"]),
        ("evidence-vs-CCL judgments",
         f"{dk['locality']['w500']['pairwiseWithinJudgment']['commercial_courts_law | evidence_law']['judgments']:,}",
         ["DOCKET.md", "THEORY_LOG.md", "CLAIM_ECOLOGIES.md"]),
        ("evidence, proof dispute",
         f"{dk['evidenceCodeOrProofDispute']['cites Evidence Law, proof dispute in recital']['hybridPct']}",
         ["DOCKET.md"]),
        ("evidence, no proof marker",
         f"{dk['evidenceCodeOrProofDispute']['cites Evidence Law, no proof marker']['hybridPct']}",
         ["DOCKET.md"]),
        ("proof dispute without the code",
         f"{dk['evidenceCodeOrProofDispute']['proof dispute, does NOT cite Evidence Law']['hybridPct']}",
         ["DOCKET.md"]),
        ("fee claim with law practice",
         f"{dk['feeArticleStressTest']['fee claim, cites law practice law']['hybridPct']}",
         ["DOCKET.md"]),
        ("fee claim without law practice",
         f"{dk['feeArticleStressTest']['fee claim, no law practice law']['hybridPct']}",
         ["DOCKET.md"]),
        ("set-of-codes excess",
         f"{dk['judgmentLevelVariance']['byGrouping']['set of codes cited']['excessPts']}",
         ["DOCKET.md", "THEORY_LOG.md", "CLAIM_ECOLOGIES.md"]),
        ("docket stratum excess",
         f"{dk['judgmentLevelVariance']['byGrouping']['docket stratum (all three)']['excessPts']}",
         ["DOCKET.md", "THEORY_LOG.md", "CLAIM_ECOLOGIES.md"]),
        ("arbitration in the longest band",
         f"{dk['byReasonsLengthBand']['byInstrument']['arbitration_law']['3']}",
         ["DOCKET.md", "THEORY_LOG.md", "CLAIM_ECOLOGIES.md"]),
        ("corpus longest band",
         f"{dk['byReasonsLengthBand']['corpus']['3']}",
         ["DOCKET.md", "THEORY_LOG.md", "CLAIM_ECOLOGIES.md"]),
        # --- the locality construct check and the prediction test
        ("locality related overall",
         f"{lg['withinW500']['overall']['relatedPct']}",
         ["DOCKET.md", "THEORY_LOG.md", "CLAIM_ECOLOGIES.md"]),
        ("locality related, evidence",
         f"{lg['withinW500']['evidence_law']['relatedPct']}",
         ["DOCKET.md", "THEORY_LOG.md", "CLAIM_ECOLOGIES.md"]),
        ("locality related, commercial courts",
         f"{lg['withinW500']['commercial_courts_law']['relatedPct']}",
         ["DOCKET.md", "THEORY_LOG.md", "CLAIM_ECOLOGIES.md"]),
        ("locality unrelated, commercial courts",
         f"{lg['withinW500']['commercial_courts_law']['unrelatedPct']}",
         ["DOCKET.md"]),
        ("brier grand mean",
         f"{dm['brier']['grandMeanOnly']}",
         ["DOCKET.md", "CLAIM_ECOLOGIES.md"]),
        ("brier docket only",
         f"{dm['brier']['model0_docketOnly']}",
         ["DOCKET.md", "CLAIM_ECOLOGIES.md"]),
        ("brier docket plus codes",
         f"{dm['brier']['model1_docketPlusCodes']}",
         ["DOCKET.md", "CLAIM_ECOLOGIES.md"]),
        ("codes share of improvement",
         f"{dm['improvement']['relativeShareOfTotalImprovementPct']}",
         ["DOCKET.md", "THEORY_LOG.md", "CLAIM_ECOLOGIES.md"]),
        ("arbitration adjustment",
         f"{dm['codeAdjustments']['arbitration_law']}", ["DOCKET.md"]),
        # --- the doctrinal companion programme
    ]
    C4 = cm["phase4_resolution"]
    CW = cm["loc_w500"]
    CP = CW["phase5_8_9_profiles"]
    C7 = {c: {d["source"]: d for d in v} for c, v in CW["phase7_null"].items()}
    C12, C12b = CW["phase12_sameJudgment"], cm["loc_block"]["phase12_sameJudgment"]
    C15, C16 = CW["phase15_leaveArticleOut"], CW["phase16b_deboilerplated"]
    C22, C26 = CW["phase22_23_stability"], CW["phase26_signature"]
    D = ["DOCTRINE.md"]
    EV, CL = "evidence_law", "commercial_courts_law"
    IR = "commercial_courts_implementing_regulation"
    SP = "sharia_procedure_law"
    out += [
        ("resolved share", f"{C4['resolvedPct']}", D),
        ("untraced hadith share", f"{C4['untracedHadithPct']}", D),
        ("merged by alias handling", f"{C4['mergedByAliasHandlingPct']}", D),
        ("Ibn Taymiyya as title", f"{C4['ibnTaymiyyaAsTitleShaykhAlIslamPct']}", D),
        ("evidence effective sources", f"{CP[EV]['effectiveSources']}", D),
        ("evidence hhi", f"{CP[EV]['hhi']}", D),
        ("evidence top3", f"{CP[EV]['coverageTop3']}", D),
        ("ccl hhi", f"{CP[CL]['hhi']}", D),
        ("ccl effective sources", f"{CP[CL]['effectiveSources']}", D),
        ("ccir hhi", f"{CP[IR]['hhi']}", D),
        ("ccir effective sources", f"{CP[IR]['effectiveSources']}", D),
        ("sharia procedure hhi", f"{CP[SP]['hhi']}", D),
        ("sharia procedure effective sources", f"{CP[SP]['effectiveSources']}", D),
        ("ibn al-Qayyim P(code|source)",
         f"{[r for r in CP[EV]['top'] if r['source'] == 'J.IBN_QAYYIM'][0]['P_code_given_source']}", D),
        ("kashshaf z in ccir", f"{C7[IR]['B.KASHSHAF']['z']}", D),
        ("ibn taymiyya z in ccir", f"{C7[IR]['J.IBN_TAYMIYYA']['z']}", D),
        ("majmu z in ccir", f"{C7[IR]['B.MAJMU_FATAWA']['z']}", D),
        ("settled practice z in evidence",
         f"{C7[EV]['GENERIC.principle.settled']['z']}", D),
        ("custom z in evidence", f"{C7[EV]['GENERIC.custom.trade']['z']}", D),
        ("ibn al-Qayyim z in evidence", f"{C7[EV]['J.IBN_QAYYIM']['z']}", D),
        ("abu dawud z in ccl", f"{C7[CL]['H.ABU_DAWUD']['z']}", D),
        ("quran z in sharia procedure",
         f"{C7[SP]['GENERIC.quran.citation']['z']}", D),
        ("ibn taymiyya z in ccl", f"{C7[CL]['J.IBN_TAYMIYYA']['z']}", D),
        ("ibn taymiyya z in evidence", f"{C7[EV]['J.IBN_TAYMIYYA']['z']}", D),
        ("same-judgment cosine", f"{C12['cosine']}", D),
        ("same-judgment null", f"{C12['nullCosineMean']}", D),
        ("same-judgment z", f"{C12['z']}", D),
        ("same-judgment block cosine", f"{C12b['cosine']}", D),
        ("same-judgment block z", f"{C12b['z']}", D),
        ("ccir same-judgment cosine", f"{CW['phase12_sameJudgment_ccir']['cosine']}", D),
        ("ccir same-judgment z", f"{CW['phase12_sameJudgment_ccir']['z']}", D),
        ("relatedness-corrected cosine",
         f"{CW['phase13_relatednessSensitivity']['correctedCosine']}", D),
        ("evidence article drop cosine",
         f"{C15[EV]['empirical']['cosineFullVsDropped']}", D),
        ("evidence named article drop cosine",
         f"{C15[EV]['named']['cosineFullVsDropped']}", D),
        ("ccir article drop cosine", f"{C15[IR]['empirical']['cosineFullVsDropped']}", D),
        ("ccl article drop cosine", f"{C15[CL]['empirical']['cosineFullVsDropped']}", D),
        ("sharia procedure article drop cosine",
         f"{C15[SP]['empirical']['cosineFullVsDropped']}", D),
        ("ccir mentions dropped", f"{C15[IR]['empirical']['mentionsDroppedPct']}", D),
        ("evidence mentions dropped", f"{C15[EV]['named']['mentionsDroppedPct']}", D),
        ("boilerplate share removed", f"{C16['courtMentionsRemovedPct']}", D),
        ("de-boilerplated same-judgment z",
         f"{C16['phase12_deboilerplated']['z']}", D),
        ("de-boilerplated macro F1", f"{C16['phase26_deboilerplated']['macroF1']}", D),
        ("de-boilerplated control macro F1",
         f"{C16['phase27_deboilerplatedShuffled']['macroF1']}", D),
        ("signature accuracy", f"{C26['accuracy']}", D),
        ("signature macro F1", f"{C26['macroF1']}", D),
        ("shuffled signature accuracy",
         f"{CW['phase27_shuffledControl']['accuracy']}", D),
        ("shuffled signature macro F1",
         f"{CW['phase27_shuffledControl']['macroF1']}", D),
        ("signature majority baseline", f"{C26['majorityBaseline']}", D),
        ("evidence recall", f"{C26['uniformPrior']['perCode'][EV]['recall']}", D),
        ("ccir recall", f"{C26['uniformPrior']['perCode'][IR]['recall']}", D),
        ("evidence precision", f"{C26['uniformPrior']['perCode'][EV]['precision']}", D),
        ("evidence year cosine", f"{C22[EV]['meanYearCosine']}", D),
        ("ccl year cosine", f"{C22[CL]['meanYearCosine']}", D),
        ("ccir year cosine", f"{C22[IR]['meanYearCosine']}", D),
        ("evidence city cosine", f"{C22[EV]['meanCityCosine']}", D),
        ("ccl min city cosine", f"{C22[CL]['minCityCosine']}", D),
        ("untraceable, sharia procedure",
         f"{CW['phase29_untraceable'][SP]['untraceablePct']}", D),
        ("untraceable, ccir", f"{CW['phase29_untraceable'][IR]['untraceablePct']}", D),
        ("untraceable, evidence", f"{CW['phase29_untraceable'][EV]['untraceablePct']}", D),
        ("untraceable, ccl", f"{CW['phase29_untraceable'][CL]['untraceablePct']}", D),
        ("evidence retrieval top3", f"{CW['phase28_retrieval'][EV]['top3']}", D),
        ("ccir retrieval top5", f"{CW['phase28_retrieval'][IR]['top5']}", D),
        ("repeated wording family share",
         f"{cm['phase17_propositions']['sharePartOfARepeatedFamily']}", D),
        ("ccir top fingerprint share",
         f"{CW['phase16_templates'][IR][2]['topFingerprintShare']}", D),
        ("ccl top fingerprint share",
         f"{CW['phase16_templates'][CL][0]['topFingerprintShare']}", D),
        # --- the foresight and AI-transition programme
    ]
    FS, FL = fo["scalarTargets"], ["FORESIGHT.md"]
    AV, EN = fo["articleVisibility"], fo["newEntrants"]
    LL, RD = fo["leadLag"], fo["retrievalDecay"]
    CPP, UP = fo["companionPersistence"], fo["newCodeUptake"]
    A, B, C, DD = (aib["A_statutoryUse"], aib["B_courtVsBar"],
                   aib["C_doctrinalDiversity"], aib["D_traceability"])
    E, FF, G = (aib["E_hybridReasoning"], aib["F_templateConcentration"],
                aib["G_uptakeVelocity"])
    FC = {f["forecast_id"]: f for f in fl["forecasts"]}
    out += [
        ("mentions in the temporal window", f"{fo['mentionsUsed']:,}", FL),
        ("thinnest quarter", f"{min(fo['judgmentsWithAuthorityByPeriod'].values())}", FL),
        ("distinct articles cited", f"{A['distinctArticlesCited']}", FL),
        ("court article HHI at cutoff", f"{A['courtArticleHHI']}", FL),
        ("top-50 share of court citations", f"{A['top50ShareOfCourtCitations']}", FL),
        ("entrants per quarter", f"{A['meanTop50EntrantsPerQuarter']}", FL),
        ("court/party top-20 jaccard", f"{B['courtTop20VsPartyTop20Jaccard']}", FL),
        ("canonical identities", f"{C['distinctCanonicalIdentities']}", FL),
        ("named fiqh share trailing year",
         f"{C['corpusNamedFiqhShareOfFiqhTrailingYear']}", FL),
        ("resolved statute pct", f"{DD['resolvedStatutePct']}", FL),
        ("named source pct", f"{DD['namedSourcePct']}", FL),
        ("unnamed pct", f"{DD['unnamedPct']}", FL),
        ("statute-only share", f"{E['statuteOnlyPct']}", FL),
        ("hybrid share", f"{E['hybridPct']}", FL),
        ("distinct fingerprints", f"{FF['distinctFingerprints']:,}", FL),
        ("circulating fingerprints", f"{FF['circulatingFingerprints']}", FL),
        ("court mentions in circulating wording",
         f"{FF['courtMentionsInCirculatingWordingPct']}", FL),
        ("first seen in court voice", f"{G['shareFirstSeenInCourtVoice']}", FL),
        ("first seen in party voice", f"{G['shareFirstSeenInPartyVoice']}", FL),
        ("first seen same quarter", f"{G['shareFirstSeenSameQuarter']}", FL),
        ("articles with both first uses",
         f"{G['articlesWithBothFirstUsesObserved']}", FL),
        ("named fiqh best baseline mae",
         f"{FS['namedFiqhShareOfFiqh']['mae']['MEAN']}", FL),
        ("non-statutory best baseline mae",
         f"{FS['nonStatutoryShareOfCourtMentions']['mae']['MA3']}", FL),
        ("overlap best baseline mae",
         f"{FS['courtPartyTop20Jaccard']['mae']['MA3']}", FL),
        ("hhi best baseline mae", f"{FS['courtArticleHHI']['mae']['LAST']}", FL),
        ("ccl instrument share mae",
         f"{FS['commercialCourtsLawShareOfInstruments']['mae']['LAST']}", FL),
        ("ctl share mae",
         f"{FS['civilTransactionsLawShareOfCourtCitations']['mae']['LAST']}", FL),
        ("shrink skill on non-statutory share",
         f"{FS['nonStatutoryShareOfCourtMentions']['modelSkill']['SHRINK']['meanSkillVsBestBaseline']}", FL),
        ("shrink worst fold",
         f"{FS['nonStatutoryShareOfCourtMentions']['modelSkill']['SHRINK']['worstFoldSkill']}", FL),
        ("drift skill on named fiqh",
         f"{FS['namedFiqhShareOfFiqh']['modelSkill']['DRIFT']['meanSkillVsBestBaseline']}", FL),
        ("drift worst fold on named fiqh",
         f"{FS['namedFiqhShareOfFiqh']['modelSkill']['DRIFT']['worstFoldSkill']}", FL),
        ("top-50 jaccard persistence", f"{AV['meanTopKJaccard_prevPeriod']}", FL),
        ("top-50 jaccard worst fold", f"{AV['worstTopKJaccard_prevPeriod']}", FL),
        ("top-50 jaccard ma3", f"{AV['meanTopKJaccard_ma3']}", FL),
        ("top-10 jaccard persistence",
         f"{fo['articleVisibilityTop10']['meanTopKJaccard_prevPeriod']}", FL),
        ("share mae LAST", f"{AV['shareMaeMean']['LAST']}", FL),
        ("share mae MA3", f"{AV['shareMaeMean']['MA3']}", FL),
        ("entrant candidates", f"{EN['candidates']:,}", FL),
        ("entrant base rate", f"{round(100 * EN['baseRate'], 2)}", FL),
        ("entrant precision, court share",
         f"{round(100 * EN['courtShare']['precisionAtNTrue'], 2)}", FL),
        ("entrant lift, court share", f"{EN['courtShare']['liftOverBaseRate']}", FL),
        ("entrant lift, party share", f"{EN['partyShare']['liftOverBaseRate']}", FL),
        ("entrant lift, momentum", f"{EN['momentum']['liftOverBaseRate']}", FL),
        ("court persistence r", f"{LL['meanCourtPersistenceR']}", FL),
        ("party lead r", f"{LL['meanPartyLeadR']}", FL),
        ("party partial r", f"{LL['meanPartyPartialR']}", FL),
        ("decay whole judgment h1",
         f"{RD['h1']['meanCoverage']['WHOLE_JUDGMENT']}", FL),
        ("decay court reasoning h1",
         f"{RD['h1']['meanCoverage']['COURT_REASONING']}", FL),
        ("decay top50 h1",
         f"{RD['h1']['meanCoverage']['STATUTE_ONLY_TOP50']}", FL),
        ("decay court reasoning h4",
         f"{RD['h4']['meanCoverage']['COURT_REASONING']}", FL),
        ("decay top50 h4",
         f"{RD['h4']['meanCoverage']['STATUTE_ONLY_TOP50']}", FL),
        ("companion universe coverage",
         f"{RD['doctrinalCompanionUniverse']['meanCoverage']}", FL),
        ("companion jaccard, evidence",
         f"{CPP['evidence_law']['meanTopKJaccard']}", FL),
        ("companion jaccard, ccl",
         f"{CPP['commercial_courts_law']['meanTopKJaccard']}", FL),
        ("companion jaccard, ccir",
         f"{CPP['commercial_courts_implementing_regulation']['meanTopKJaccard']}", FL),
        ("ctl first court quarter", f"{UP['firstCourtQuarter']}", FL),
        ("ctl first top50 quarter", f"{UP['firstQuarterInCourtTop50']}", FL),
        ("ctl quarters to top50",
         f"{UP['quartersFromFirstCourtUseToTop50']}", FL),
        ("forecast: ctl share",
         f"{FC['ctl_court_share@1446Q2']['prediction']['pointEstimate']}", FL),
        ("forecast: overlap",
         f"{FC['court_party_top20_jaccard@1446Q2']['prediction']['pointEstimate']}", FL),
        ("forecast: retrieval coverage",
         f"{FC['retrieval_coverage_h1@1446Q2']['prediction']['pointEstimate']}", FL),
        ("ledger hash", fl["ledgerHash"], FL),
        # --- the AI-transition layer
    ]
    AT = ["AI_TRANSITION.md"]
    SA, MIS = fo["speakerAwareRetrieval"], fo["temporalMisalignment"]
    CPP2 = fo["companionPersistence"]
    out += [
        ("registry events", f"{len(reg['events'])}", AT),
        ("events before cutoff", f"{b2['eventCounts']['beforeCutoff']}", AT),
        ("event studies permitted", f"{amap['eventStudiesPermittedToday']}", AT),
        ("judgments scanned by the radar",
         f"{rad['judgmentsScanned']:,}", AT),
        ("radar L3", f"{rad['L3_count']}", AT),
        ("radar L2", f"{rad['byLevel'].get('L2', 0)}", AT),
        ("radar L1", f"{rad['byLevel'].get('L1', 0)}", AT),
        ("radar CONTEXT", f"{rad['byLevel'].get('CONTEXT', 0)}", AT),
        ("party-only universe growth", f"{SA['meanUniverseGrowthPct']}", AT),
        ("party-only coverage added",
         f"{SA['meanCoverageAddedByPartyOnly']}", AT),
        ("party-only precision", f"{SA['meanPartyOnlyPrecision']}", AT),
        ("coverage points per 10pct growth",
         f"{SA['coveragePointsPer10pctUniverseGrowth']}", AT),
        ("speaker-aware folds", f"{SA['folds']}", AT),
        ("misalignment h1 never seen",
         f"{MIS['h1']['meanCitationShareToNeverSeenArticles']}", AT),
        ("misalignment h1 top50 displaced",
         f"{MIS['h1']['meanTop50DisplacedPct']}", AT),
        ("misalignment h4 never seen",
         f"{MIS['h4']['meanCitationShareToNeverSeenArticles']}", AT),
        ("misalignment h4 top50 displaced",
         f"{MIS['h4']['meanTop50DisplacedPct']}", AT),
        ("misalignment h4 rank displacement",
         f"{MIS['h4']['meanRankDisplacementTop200']}", AT),
        ("companions not in frozen set",
         f"{MIS['companionsNotInFrozenSet']['meanShareOfNextPeriodMentions']}", AT),
        ("backfill rows", f"{fo['companionBackfill']['backfillRows']:,}", AT),
        ("ccl companion steps",
         f"{CPP2['commercial_courts_law']['steps']}", AT),
        ("ccir companion steps",
         f"{CPP2['commercial_courts_implementing_regulation']['steps']}", AT),
        ("ccl companion jaccard, backfilled",
         f"{CPP2['commercial_courts_law']['meanTopKJaccard']}", AT),
        ("court persistence r, in the AI note",
         f"{fo['leadLag']['meanCourtPersistenceR']}", AT),
        ("party partial r, in the AI note",
         f"{fo['leadLag']['meanPartyPartialR']}", AT),
        ("first seen in court voice, in the AI note",
         f"{aib['G_uptakeVelocity']['shareFirstSeenInCourtVoice']}", AT),
        ("articles with both first uses, in the AI note",
         f"{aib['G_uptakeVelocity']['articlesWithBothFirstUsesObserved']}", AT),
        # --- the Board of Grievances access audit
    ]
    BA = ["BOG_ACCESS.md"]
    PUB = fo["publicationProfile"]["compositionSwings"]
    out += [
        ("bog access verdict", bau["verdict"], BA),
        ("event class", xm["eventClass"], BA),
        ("event studies feasible", f"{xm['eventStudiesFeasible']}", BA),
        ("matrix rows", f"{len(xm['matrix'])}", BA),
        ("forecasts tagged by channel", f"{xm['forecastsTagged']}", BA),
        ("publication periods", f"{fo['publicationProfile']['periods']}", BA),
        ("median reasons length, first",
         f"{PUB['medianReasonChars']['first']}", BA),
        ("median reasons length, last",
         f"{PUB['medianReasonChars']['last']}", BA),
        ("median reasons length, max move",
         f"{PUB['medianReasonChars']['maxQuarterOnQuarterChange']}", BA),
        ("fees claims, first", f"{PUB['share_feesClaim']['first']}", BA),
        ("fees claims, last", f"{PUB['share_feesClaim']['last']}", BA),
        ("fees claims, max move",
         f"{PUB['share_feesClaim']['maxQuarterOnQuarterChange']}", BA),
        ("damages claims, first", f"{PUB['share_damagesClaim']['first']}", BA),
        ("damages claims, last", f"{PUB['share_damagesClaim']['last']}", BA),
        ("proof disputes, max move",
         f"{PUB['share_proofDispute']['maxQuarterOnQuarterChange']}", BA),
        ("radar L3, in the access note", f"{rad['L3_count']}", BA),
        ("judgments scanned, in the access note",
         f"{rad['judgmentsScanned']:,}", BA),
        # --- the horizon scanner and the detectors
    ]
    H = ["HORIZON.md"]
    EN, LL = hz["phase4_5_entrants"], hz["phase7_leadLagHeterogeneity"]
    SA, AR = hz["phase19_20_salienceBaseline"], hz["phase23_24_architectures"]
    NL, RT = hz["phase6_newLawMonitor"], hz["phase22_refreshTriggers"]
    AB, PC = dt["alarmBudget"], dt["phase25_positiveControl"]
    FMC = hz["phase1_forecastabilityMap"]["counts"]
    out += [
        ("forecastable targets", f"{FMC['FORECAST']}", H),
        ("detect targets", f"{FMC['DETECT']}", H),
        ("scorable quarters", f"{len(hz['phase3_maturityRule']['scorable'])}", H),
        ("entrant base rate", f"{EN['meanBaseRate']}", H),
        ("entrant precision, court share",
         f"{EN['meanPrecisionAtNTrue']['courtShare']}", H),
        ("entrant lift, court share", f"{EN['liftOverBaseRate']['courtShare']}", H),
        ("entrant precision, combined",
         f"{EN['meanPrecisionAtNTrue']['combined']}", H),
        ("entrant precision, party share",
         f"{EN['meanPrecisionAtNTrue']['partyShare']}", H),
        ("entrant near-boundary", f"{EN['meanNearBoundaryEntrants']}", H),
        ("entrant long jumps", f"{EN['meanLongJumpEntrants']}", H),
        ("new-law instruments in window",
         f"{NL['instrumentsArrivingInWindow']}", H),
        ("new-law reached top 50", f"{NL['reachedTop50']}", H),
        ("new-law median quarters to top 50",
         f"{NL['medianQuartersToTop50']}", H),
        ("lead-lag, all articles",
         f"{LL['bySubset']['ALL']['meanPartialR']}", H),
        ("lead-lag, rare articles",
         f"{LL['bySubset']['RARE_ARTICLES_BOTTOM_HALF']['meanPartialR']}", H),
        ("lead-lag, commercial courts law",
         f"{LL['bySubset']['COMMERCIAL_COURTS_LAW']['meanPartialR']}", H),
        ("rank autocorrelation", f"{SA['rankAutocorrelation']}", H),
        ("top decile persistence", f"{SA['topDecilePersistence']}", H),
        ("bottom-half mobility", f"{SA['bottomHalfToTopDecileMobility']}", H),
        ("entrant survival", f"{SA['newEntrantSurvivalOneQuarter']}", H),
        ("article hhi mean", f"{SA['articleHhiMean']}", H),
        ("hybrid recall",
         f"{AR['summary']['SPEAKER_AWARE_HYBRID']['meanCourtAuthorityRecall']}", H),
        ("hybrid size",
         f"{AR['summary']['SPEAKER_AWARE_HYBRID']['meanUniverseSize']}", H),
        ("hybrid contamination",
         f"{AR['summary']['SPEAKER_AWARE_HYBRID']['meanPartyContamination']}", H),
        ("whole judgment recall",
         f"{AR['summary']['WHOLE_JUDGMENT']['meanCourtAuthorityRecall']}", H),
        ("whole judgment contamination",
         f"{AR['summary']['WHOLE_JUDGMENT']['meanPartyContamination']}", H),
        ("top200 recall",
         f"{AR['summary']['STATUTE_ONLY_TOP200']['meanCourtAuthorityRecall']}", H),
        ("detectors run", f"{AB['detectorsRun']}", H),
        ("evaluable periods", f"{AB['periodsEvaluatedTotal']}", H),
        ("signals total", f"{AB['signalsTotal']}", H),
        ("alarm rate", f"{AB['alarmRate']}", H),
        ("confirmed rate", f"{AB['confirmedRate']}", H),
        ("positive control first signal", f"{PC['firstSignalQuarter']}", H),
        ("positive control delay", f"{PC['detectionDelayQuarters']}", H),
        ("refresh, earliest trigger",
         f"{RT['earliestTriggeredHorizonQuarters']}", H),
    ]
    return out


def main():
    bad = []
    cache = {}
    for label, value, docs in facts():
        for doc in docs:
            text = cache.setdefault(
                doc, (HERE / doc).read_text(encoding="utf-8"))
            if value not in text:
                bad.append(f"  {label} = {value} is not in {doc}")
    checked = sum(len(d) for _, _, d in facts())
    if bad:
        print(f"{len(bad)} figure(s) in the contemporary notes no longer "
              f"match the results:")
        print("\n".join(bad))
        return 1
    print(f"all {checked} guarded figures in the contemporary notes match "
          f"the results files")
    return 0


if __name__ == "__main__":
    sys.exit(main())
