#!/usr/bin/env python3
"""Refuse to typeset a result that predates the code which produced it.

check_numbers.py stops a figure being typed by hand. It cannot stop the other
way a manuscript goes wrong, which is subtler and was found in this project by
reading rather than by any guard: the figure is generated, the generator reads
a JSON, and the JSON was written before the extractor underneath it was fixed.
Every check passes and the paper still reports superseded numbers.

That happened here. The regular-expression that finds a statutory citation was
missing a class of Arabic prefixes and was corrected; two analyses were not
re-run afterwards, and paper 9 typeset their output for a week. Re-running them
moved the pooled comparison it reported, and the paired test added at the same
time reversed its sign.

So: for each `<name>_results.json`, find the script that writes it, follow that
script's local imports transitively, and fail if any of those files is newer
than the JSON. mtimes do not survive a fresh clone --- every file arrives at
checkout time --- so on a clean checkout this passes and says nothing, which is
correct: there the results were regenerated by reproduce.sh anyway. It is aimed
at the working tree, which is where the defect lives.

    python3 docs/research/check_fresh.py
"""

import ast
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC = HERE / "arabic_paper"

# reversal_model.py writes reversal_model_results.json and, run with a window,
# reversal_model_1439_1444_results.json. The producer is the longest script
# name that prefixes the JSON name.
SUFFIX = re.compile(r"_results\.json$")


def producer(results):
    stem = SUFFIX.sub("", results.name)
    while stem:
        candidate = SRC / f"{stem}.py"
        if candidate.exists():
            return candidate
        stem = stem.rpartition("_")[0]
    return None


def local_imports(script, seen=None):
    """The script, plus every module in this directory it imports, recursively."""
    seen = seen if seen is not None else set()
    if script in seen:
        return seen
    seen.add(script)
    try:
        tree = ast.parse(script.read_text(encoding="utf-8"))
    except (SyntaxError, OSError):
        return seen
    names = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            names += [a.name for a in node.names]
        elif isinstance(node, ast.ImportFrom) and node.module:
            names.append(node.module)
    for name in names:
        child = SRC / f"{name.split('.')[0]}.py"
        if child.exists():
            local_imports(child, seen)
    return seen


def main():
    stale = []
    checked = 0
    for results in sorted(SRC.glob("*_results.json")):
        script = producer(results)
        if script is None:
            continue
        checked += 1
        written = results.stat().st_mtime
        newer = sorted(d.name for d in local_imports(script)
                       if d.stat().st_mtime > written)
        if newer:
            stale.append((results.name, newer))
    if stale:
        print(f"{len(stale)} result file(s) older than the code that writes "
              f"them --- re-run before building:")
        for name, newer in stale:
            print(f"  {name}\n    newer: {', '.join(newer)}")
        return 1
    print(f"all {checked} result files are newer than their code")
    return 0


if __name__ == "__main__":
    sys.exit(main())
