#!/usr/bin/env python3
"""Turn a manuscript into a sheet for checking a publisher's proof.

A proof is the last moment anything can be fixed, and it is checked once,
usually quickly, usually by reading. Reading is the wrong instrument: the eye
slides over a digit that changed and stops at a comma that did not.

Every measurement in these manuscripts is typeset from a generated macro, so
the source knows exactly which numbers must appear and in what order. This
walks main.tex, pulls out every macro use in reading order with its value and
the words around it, and prints a sheet to tick against the proof. What the
author then does is not read the proof --- it is compare two lists.

    python3 make_proof_sheet.py comparison_paper   ->  proof_sheet.md
"""

import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
MACRO = re.compile(r"\\(n[A-Z][A-Za-z]*)\{\}")


def values(paper):
    out = {}
    for name, raw in re.findall(
            r"\\newcommand\{\\(\w+)\}\{([^{}]*(?:\{,\}[^{}]*)*)\}",
            (paper / "numbers.tex").read_text(encoding="utf-8")):
        out[name] = raw.replace("{,}", ",").replace("$-$", "\u2212")
    return out


def context(line, m, width=42):
    """The words either side, with the LaTeX stripped out."""
    def clean(t):
        t = re.sub(r"\\[a-zA-Z]+\{([^{}]*)\}", r"\1", t)
        t = re.sub(r"\\[a-zA-Z]+\{\}|\\[a-zA-Z]+|[{}$~]", " ", t)
        t = t.replace("---", "\u2014").replace("--", "\u2013")
        # table markup reads as noise in a context line: the row is still
        # identifiable without the ampersands and the row terminator
        t = t.replace("\\\\", " ").replace("&", " \u00b7 ").replace("%", "")
        return re.sub(r"\s+", " ", t).strip(" \u00b7 ")
    return clean(line[:m.start()])[-width:], clean(line[m.end():])[:width]


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    paper = HERE / sys.argv[1]
    src = paper / "main.tex"
    if not src.exists():
        sys.exit(f"no manuscript at {src}")
    vals = values(paper)
    lines = src.read_text(encoding="utf-8").splitlines()
    start = next((i for i, l in enumerate(lines)
                  if l.strip().startswith("\\begin{document}")), 0)

    rows, seen, missing = [], set(), set()
    for line in lines[start:]:
        if line.lstrip().startswith("%"):
            continue
        for m in MACRO.finditer(line):
            name = m.group(1)
            if name not in vals:
                missing.add(name)
                continue
            before, after = context(line, m)
            rows.append((len(rows) + 1, vals[name], name, before, after))
            seen.add(name)

    out = [f"# Proof sheet — `{sys.argv[1]}`", "",
           "Generated by `make_proof_sheet.py` from `main.tex` and "
           "`numbers.tex`. Do not read the proof. **Compare it to this.**", "",
           "## Every measurement, in reading order", "",
           "| # | Must read | Macro | Where |", "|---:|---|---|---|"]
    for i, val, name, before, after in rows:
        where = f"…{before} **[…]** {after}…".replace("|", "\\|")
        out.append(f"| {i} | **{val}** | `{name}` | {where} |")

    unused = sorted(set(vals) - seen)
    out += ["", f"**{len(rows)} appearances of {len(seen)} distinct "
                f"measurements.**", ""]
    if unused:
        out += ["Generated but never used in the manuscript — nothing to check,"
                " listed so the absence is deliberate rather than missed: "
                + ", ".join(f"`{u}`" for u in unused), ""]
    if missing:
        out += ["> **A macro is used that `numbers.tex` does not define: "
                + ", ".join(f"`{m}`" for m in sorted(missing))
                + ". Fix before checking the proof.**", ""]
    out += [
        "## What a typesetter breaks, and this list will not catch", "",
        "- **Figure and table numbering and captions.** Read every caption",
        "  against its figure. A caption attached to the wrong figure survives",
        "  every automated check ever written.",
        "- **Figure quality.** The publisher re-renders. Look at the actual",
        "  lines and labels at print size, not at a thumbnail.",
        "- **Special characters.** Macrons, em-dashes, Arabic transliteration,",
        "  and quotation marks are where conversion damage lands.",
        "- **Footnote and reference numbering**, and whether any note lost its",
        "  anchor in the text.",
        "- **Your name, affiliation and ORCID.** Character by character.",
        "- **The references list**: every entry present, in order, with its",
        "  volume, year and pages intact.",
        "",
        "## What a proof is not for", "",
        "A proof corrects errors introduced in production, and errors of fact",
        "that would otherwise be published. It is not a chance to improve a",
        "sentence, add a citation, or soften a claim. Publishers charge for",
        "rewriting at this stage and editors remember it. If something is",
        "wrong, say exactly what it should read; if something is merely worse",
        "than it could be, leave it.",
    ]
    (paper / "proof_sheet.md").write_text("\n".join(out) + "\n",
                                          encoding="utf-8")
    print(f"wrote {sys.argv[1]}/proof_sheet.md — {len(rows)} appearances of "
          f"{len(seen)} measurements"
          + (f", {len(unused)} unused" if unused else "")
          + (f", {len(missing)} UNDEFINED" if missing else ""))


if __name__ == "__main__":
    main()
