#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Build a single unified retrieval index over every Arabic LLM-ready layer.

Normalizes the per-law enrichment layers — Companies Law, PDPL (law +
implementing regulation), and the Investment Law (law + implementing
regulations) — into one flat JSONL index of retrieval records sharing a common
schema, so a single search can query the whole corpus.

Each source layer already carries mechanical retrieval metadata (llm_title /
retrieval_title / article_path / keywords / search_queries).  This generator only
projects those fields into a common shape and stamps the owning law's friendly
Arabic title and corpus key.  It does not alter, summarize, translate, or
re-derive any legal text.  Arabic governs.

Read-only over its inputs; deterministic and idempotent over its output.
"""

from __future__ import annotations

import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(ROOT, "data", "corpus_unified_index")
INDEX = os.path.join(OUT_DIR, "corpus_unified_llm_index.jsonl")
SUMMARY = os.path.join(OUT_DIR, "corpus_unified_llm_index_summary.json")

# (relative layer file, corpus key, default law_component when a record omits it)
LAYERS = [
    ("data/official_arabic_legal_llm/companies_law_m132_1443_official_arabic_legal_llm_001_281.json",
     "companies_law", "law"),
    ("data/pdpl_arabic_legal_llm/pdpl_arabic_law_legal_llm_001_043.json",
     "pdpl", "law"),
    ("data/pdpl_arabic_legal_llm/pdpl_implementing_regulation_arabic_legal_llm_001_038.json",
     "pdpl", "implementing_regulation"),
    ("data/investment_arabic_legal_llm/investment_law_legal_llm_001_016.json",
     "investment", "law"),
    ("data/investment_arabic_legal_llm/investment_regulation_legal_llm_001_037.json",
     "investment", "implementing_regulation"),
    ("data/civil_arabic_legal_llm/civil_transactions_law_legal_llm_001_721.json",
     "civil", "law"),
    ("data/gtpl_arabic_legal_llm/gtpl_law_legal_llm_001_099.json",
     "gtpl", "law"),
    ("data/gtpl_arabic_legal_llm/gtpl_regulation_legal_llm_001_157.json",
     "gtpl", "implementing_regulation"),
    ("data/labor_arabic_legal_llm/labor_law_legal_llm_001_245.json",
     "labor", "law"),
    ("data/labor_arabic_legal_llm/labor_regulation_legal_llm_001_040.json",
     "labor", "implementing_regulation"),
    ("data/labor_arabic_legal_llm/labor_annex1_legal_llm_001_072.json",
     "labor", "model_work_regulation"),
    ("data/labor_arabic_legal_llm/labor_annex1_violation_tables_llm.json",
     "labor", "model_work_regulation"),
    ("data/labor_arabic_legal_llm/labor_annex3_legal_llm_001_020.json",
     "labor", "recruitment_mediation_rules"),
    ("data/labor_arabic_legal_llm/labor_annex4_legal_llm_001_072.json",
     "labor", "recruitment_services_rules"),
    ("data/labor_arabic_legal_llm/labor_annex2_accessibility_tables_llm.json",
     "labor", "accessibility_arrangements"),
    ("data/labor_arabic_legal_llm/labor_annex5_contract_forms_llm.json",
     "labor", "model_contract_forms"),
    ("data/evidence_arabic_legal_llm/evidence_law_legal_llm_001_129.json",
     "evidence", "law"),
    ("data/evidence_arabic_legal_llm/evidence_electronic_rules_legal_llm_001_024.json",
     "evidence", "electronic_procedures_rules"),
    ("data/evidence_arabic_legal_llm/evidence_procedural_manuals_legal_llm_001_135.json",
     "evidence", "procedural_manuals"),
    ("data/evidence_arabic_legal_llm/evidence_expertise_rules_legal_llm_001_034.json",
     "evidence", "expertise_rules"),
    ("data/personal_status_arabic_legal_llm/personal_status_law_legal_llm_001_252.json",
     "personal_status", "law"),
    ("data/personal_status_arabic_legal_llm/personal_status_regulation_legal_llm_001_041.json",
     "personal_status", "implementing_regulation"),
    ("data/sharia_procedure_arabic_legal_llm/sharia_procedure_law_legal_llm_001_243.json",
     "sharia_procedure", "law"),
    ("data/sharia_procedure_arabic_legal_llm/sharia_procedure_regulation_legal_llm_001_637.json",
     "sharia_procedure", "implementing_regulation"),
    ("data/criminal_procedure_arabic_legal_llm/criminal_procedure_law_legal_llm_001_222.json",
     "criminal_procedure", "law"),
    ("data/criminal_procedure_arabic_legal_llm/criminal_procedure_regulation_legal_llm_001_181.json",
     "criminal_procedure", "implementing_regulation"),
    ("data/enforcement_arabic_legal_llm/enforcement_law_legal_llm_001_098.json",
     "enforcement", "law"),
    ("data/enforcement_arabic_legal_llm/enforcement_regulation_legal_llm_001_273.json",
     "enforcement", "implementing_regulation"),
    ("data/judiciary_arabic_legal_llm/judiciary_law_legal_llm_001_085.json",
     "judiciary", "law"),
    ("data/board_of_grievances_arabic_legal_llm/board_of_grievances_law_legal_llm_001_026.json",
     "board_of_grievances", "law"),
    ("data/law_practice_arabic_legal_llm/law_practice_law_legal_llm_001_056.json",
     "law_practice", "law"),
    ("data/law_practice_arabic_legal_llm/law_practice_regulation_legal_llm_001_090.json",
     "law_practice", "implementing_regulation"),
    ("data/commercial_courts_arabic_legal_llm/commercial_courts_law_legal_llm_001_096.json",
     "commercial_courts", "law"),
    ("data/commercial_courts_arabic_legal_llm/commercial_courts_regulation_legal_llm_001_281.json",
     "commercial_courts", "implementing_regulation"),
    ("data/bankruptcy_arabic_legal_llm/bankruptcy_law_legal_llm_001_231.json",
     "bankruptcy", "law"),
    ("data/bankruptcy_arabic_legal_llm/bankruptcy_regulation_legal_llm_001_098.json",
     "bankruptcy", "implementing_regulation"),
    ("data/bankruptcy_arabic_legal_llm/bankruptcy_case_rules_legal_llm_001_024.json",
     "bankruptcy", "case_procedure_rules"),
    ("data/judicial_costs_arabic_legal_llm/judicial_costs_law_legal_llm_001_023.json",
     "judicial_costs", "law"),
    ("data/judicial_costs_arabic_legal_llm/judicial_costs_regulation_legal_llm_001_017.json",
     "judicial_costs", "implementing_regulation"),
    ("data/arbitration_arabic_legal_llm/arbitration_law_legal_llm_001_058.json",
     "arbitration", "law"),
    ("data/arbitration_arabic_legal_llm/arbitration_regulation_legal_llm_001_019.json",
     "arbitration", "implementing_regulation"),
    ("data/commercial_papers_arabic_legal_llm/commercial_papers_law_legal_llm_001_121.json",
     "commercial_papers", "law"),
    ("data/commercial_register_arabic_legal_llm/commercial_register_law_legal_llm_001_029.json",
     "commercial_register", "law"),
    ("data/trade_names_arabic_legal_llm/trade_names_law_legal_llm_001_023.json",
     "trade_names", "law"),
    ("data/commercial_agencies_arabic_legal_llm/commercial_agencies_law_legal_llm_001_006.json",
     "commercial_agencies", "law"),
    ("data/chambers_of_commerce_arabic_legal_llm/chambers_of_commerce_law_legal_llm_001_066.json",
     "chambers_of_commerce", "law"),
    ("data/commercial_books_arabic_legal_llm/commercial_books_law_legal_llm_001_016.json",
     "commercial_books", "law"),
    ("data/aml_arabic_legal_llm/aml_law_legal_llm_001_052.json",
     "aml", "law"),
    ("data/aml_regulation_arabic_legal_llm/aml_regulation_legal_llm_001_025.json",
     "aml", "regulation"),
    ("data/tawtheeq_arabic_legal_llm/tawtheeq_law_legal_llm_001_057.json",
     "tawtheeq", "law"),
    ("data/tawtheeq_arabic_legal_llm/tawtheeq_regulation_legal_llm_001_031.json",
     "tawtheeq", "implementing_regulation"),
    ("data/real_estate_registration_arabic_legal_llm/real_estate_registration_law_legal_llm_001_040.json",
     "real_estate_registration", "law"),
    ("data/real_estate_registration_arabic_legal_llm/real_estate_registration_regulation_legal_llm_001_051.json",
     "real_estate_registration", "implementing_regulation"),
    ("data/real_estate_mortgage_arabic_legal_llm/real_estate_mortgage_law_legal_llm_001_046.json",
     "real_estate_mortgage", "law"),
    ("data/real_estate_finance_arabic_legal_llm/real_estate_finance_law_legal_llm_001_015.json",
     "real_estate_finance", "law"),
    ("data/real_estate_units_arabic_legal_llm/real_estate_units_law_legal_llm_001_033.json",
     "real_estate_units", "law"),
    ("data/real_estate_units_arabic_legal_llm/real_estate_units_regulation_legal_llm_001_041.json",
     "real_estate_units", "implementing_regulation"),
    ("data/foreign_ownership_arabic_legal_llm/foreign_ownership_law_legal_llm_001_015.json",
     "foreign_ownership", "law"),
    ("data/municipal_realestate_arabic_legal_llm/municipal_realestate_law_legal_llm_001_006.json",
     "municipal_realestate", "law"),
    ("data/municipal_realestate_arabic_legal_llm/municipal_realestate_regulation_legal_llm_001_035.json",
     "municipal_realestate", "implementing_regulation"),
    ("data/gcc_ownership_arabic_legal_llm/gcc_ownership_law_legal_llm_001_006.json",
     "gcc_ownership", "law"),
    ("data/terrorism_arabic_legal_llm/terrorism_law_legal_llm_001_099.json",
     "terrorism", "law"),
    ("data/terrorism_arabic_legal_llm/terrorism_regulation_legal_llm_001_028.json",
     "terrorism", "implementing_regulation"),
    ("data/juveniles_arabic_legal_llm/juveniles_law_legal_llm_001_024.json",
     "juveniles", "law"),
    ("data/juveniles_arabic_legal_llm/juveniles_regulation_legal_llm_001_013.json",
     "juveniles", "implementing_regulation"),
    ("data/whistleblower_arabic_legal_llm/whistleblower_law_legal_llm_001_037.json",
     "whistleblower", "law"),
    ("data/judicial_inspection_arabic_legal_llm/judicial_inspection_regulation_legal_llm_001_068.json",
     "judicial_inspection", "regulation"),
    ("data/qismah_arabic_legal_llm/qismah_regulation_legal_llm_001_048.json",
     "qismah", "regulation"),
    ("data/sulook_arabic_legal_llm/sulook_regulation_legal_llm_001_047.json",
     "sulook", "regulation"),
    ("data/aawan_arabic_legal_llm/aawan_regulation_legal_llm_001_035.json",
     "aawan", "regulation"),
    ("data/muslaha_arabic_legal_llm/muslaha_regulation_legal_llm_001_029.json",
     "muslaha", "regulation"),
    ("data/iflas_hudud_arabic_legal_llm/iflas_hudud_regulation_legal_llm_001_023.json",
     "iflas_hudud", "regulation"),
    ("data/judicial_documents_arabic_legal_llm/judicial_documents_regulation_legal_llm_001_023.json",
     "judicial_documents", "regulation"),
    ("data/bankruptcy_fees_arabic_legal_llm/bankruptcy_fees_regulation_legal_llm_001_020.json",
     "bankruptcy_fees", "regulation"),
    ("data/enforcement_providers_arabic_legal_llm/enforcement_providers_regulation_legal_llm_001_018.json",
     "enforcement_providers", "regulation"),
    ("data/alimony_fund_arabic_legal_llm/alimony_fund_regulation_legal_llm_001_017.json",
     "alimony_fund", "regulation"),
    ("data/judiciary_bog_arabic_legal_llm/judiciary_bog_mechanism_legal_llm_001_015.json",
     "judiciary_bog", "mechanism"),
    ("data/documentation_settlement_arabic_legal_llm/documentation_settlement_regulation_legal_llm_001_015.json",
     "documentation_settlement", "regulation"),
    ("data/mosalaha_center_arabic_legal_llm/mosalaha_center_regulation_legal_llm_001_010.json",
     "mosalaha_center", "regulation"),
    ("data/medical_reports_arabic_legal_llm/medical_reports_regulation_legal_llm_001_013.json",
     "medical_reports", "regulation"),
    ("data/marriage_non_saudi_arabic_legal_llm/marriage_non_saudi_regulation_legal_llm_001_011.json",
     "marriage_non_saudi", "regulation"),
    ("data/state_funded_lawyer_arabic_legal_llm/state_funded_lawyer_regulation_legal_llm_001_011.json",
     "state_funded_lawyer", "regulation"),
    ("data/lessor_repossession_arabic_legal_llm/lessor_repossession_regulation_legal_llm_001_007.json",
     "lessor_repossession", "regulation"),
    ("data/elitigation_guide_arabic_legal_llm/elitigation_guide_regulation_legal_llm_001_005.json",
     "elitigation_guide", "regulation"),
    ("data/judicial_training_center_arabic_legal_llm/judicial_training_center_guide_legal_llm_001_018.json",
     "judicial_training_center", "guide"),
    ("data/judgment_objection_methods_arabic_legal_llm/judgment_objection_methods_regulation_legal_llm_001_062.json",
     "judgment_objection_methods", "regulation"),
    ("data/real_estate_expropriation_arabic_legal_llm/real_estate_expropriation_law_legal_llm_001_039.json",
     "real_estate_expropriation", "law"),
    ("data/marriage_contract_hearing_arabic_legal_llm/marriage_contract_hearing_regulation_legal_llm_001_010.json",
     "marriage_contract_hearing", "regulation"),
    ("data/anti_bribery_arabic_legal_llm/anti_bribery_law_legal_llm_001_023.json",
     "anti_bribery", "law"),
    ("data/basic_law_of_governance_arabic_legal_llm/basic_law_of_governance_legal_llm_001_083.json",
     "basic_law_of_governance", "law"),
    ("data/anti_cyber_crime_arabic_legal_llm/anti_cyber_crime_law_legal_llm_001_016.json",
     "anti_cyber_crime", "law"),
    ("data/anti_harassment_arabic_legal_llm/anti_harassment_law_legal_llm_001_008.json",
     "anti_harassment", "law"),
    ("data/anti_trafficking_arabic_legal_llm/anti_trafficking_law_legal_llm_001_017.json",
     "anti_trafficking", "law"),
    ("data/council_of_ministers_arabic_legal_llm/council_of_ministers_law_legal_llm_001_032.json",
     "council_of_ministers", "law"),
    ("data/regions_arabic_legal_llm/regions_law_legal_llm_001_041.json",
     "regions", "law"),
    ("data/electronic_transactions_arabic_legal_llm/electronic_transactions_law_legal_llm_001_031.json",
     "electronic_transactions", "law"),
    ("data/allegiance_commission_arabic_legal_llm/allegiance_commission_law_legal_llm_001_025.json",
     "allegiance_commission", "law"),
    ("data/shura_council_arabic_legal_llm/shura_council_law_legal_llm_001_030.json",
     "shura_council", "law"),
    ("data/copyright_arabic_legal_llm/copyright_law_legal_llm_001_028.json",
     "copyright", "law"),
    ("data/telecommunications_arabic_legal_llm/telecommunications_law_legal_llm_001_041.json",
     "telecommunications", "law"),
    ("data/sama_arabic_legal_llm/sama_law_legal_llm_001_027.json",
     "sama", "law"),
    ("data/banking_control_arabic_legal_llm/banking_control_law_legal_llm_001_026.json",
     "banking_control", "law"),
    ("data/capital_market_arabic_legal_llm/capital_market_law_legal_llm_001_068.json",
     "capital_market", "law"),
    ("data/competition_arabic_legal_llm/competition_law_legal_llm_001_028.json",
     "competition", "law"),
    ("data/competition_regulation_arabic_legal_llm/competition_regulation_legal_llm_001_005.json",
     "competition", "regulation"),
    ("data/payment_systems_arabic_legal_llm/payment_systems_law_legal_llm_001_020.json",
     "payment_systems", "law"),
    ("data/mining_investment_arabic_legal_llm/mining_investment_law_legal_llm_001_064.json",
     "mining_investment", "law"),
    ("data/trademark_arabic_legal_llm/trademark_law_legal_llm_001_052.json",
     "trademark", "law"),
    ("data/anti_concealment_arabic_legal_llm/anti_concealment_law_legal_llm_001_020.json",
     "anti_concealment", "law"),
    ("data/insurance_control_arabic_legal_llm/insurance_control_law_legal_llm_001_025.json",
     "insurance_control", "law"),
    ("data/ecommerce_arabic_legal_llm/ecommerce_law_legal_llm_001_026.json",
     "ecommerce", "law"),
    ("data/ecommerce_regulation_arabic_legal_llm/ecommerce_regulation_legal_llm_001_020.json",
     "ecommerce", "regulation"),
    ("data/vat_arabic_legal_llm/vat_law_legal_llm_001_053.json",
     "vat", "law"),
    ("data/franchise_arabic_legal_llm/franchise_law_legal_llm_001_027.json",
     "franchise", "law"),
    ("data/franchise_regulation_arabic_legal_llm/franchise_regulation_legal_llm_001_016.json",
     "franchise", "regulation"),
    ("data/civil_aviation_arabic_legal_llm/civil_aviation_law_legal_llm_001_180.json",
     "civil_aviation", "law"),
    ("data/anti_narcotics_arabic_legal_llm/anti_narcotics_law_legal_llm_001_074.json",
     "anti_narcotics", "law"),
    ("data/traffic_arabic_legal_llm/traffic_law_legal_llm_001_086.json",
     "traffic", "law"),
    ("data/traffic_regulation_arabic_legal_llm/traffic_regulation_legal_llm_001_086.json",
     "traffic", "regulation"),
    ("data/environmental_arabic_legal_llm/environmental_law_legal_llm_001_049.json",
     "environmental", "law"),
    ("data/environmental_inspection_audit_arabic_legal_llm/environmental_inspection_audit_reg_legal_llm_001_010.json",
     "environmental_inspection_audit", "regulation"),
    ("data/environmental_violations_penalties_arabic_legal_llm/environmental_violations_penalties_reg_legal_llm_001_010.json",
     "environmental_violations_penalties", "regulation"),
    ("data/environmental_wildlife_hunting_reg_arabic_legal_llm/environmental_wildlife_hunting_reg_legal_llm_001_013.json",
     "environmental_wildlife_hunting", "regulation"),
    ("data/environmental_permits_reg_arabic_legal_llm/environmental_permits_reg_legal_llm_001_011.json",
     "environmental_permits", "regulation"),
    ("data/environmental_air_quality_arabic_legal_llm/environmental_air_quality_reg_legal_llm_001_008.json",
     "environmental_air_quality", "regulation"),
    ("data/environmental_service_providers_reg_arabic_legal_llm/environmental_service_providers_reg_legal_llm_001_012.json",
     "environmental_service_providers", "regulation"),
    ("data/environmental_fees_reg_arabic_legal_llm/environmental_fees_reg_legal_llm_001_004.json",
     "environmental_fees", "regulation"),
    ("data/rett_arabic_legal_llm/rett_law_legal_llm_001_020.json",
     "rett", "law"),
    ("data/universities_arabic_legal_llm/universities_law_legal_llm_001_058.json",
     "universities", "law"),
    ("data/privatization_arabic_legal_llm/privatization_law_legal_llm_001_045.json",
     "privatization", "law"),
    ("data/antiquities_heritage_arabic_legal_llm/antiquities_heritage_law_legal_llm_001_094.json",
     "antiquities_heritage", "law"),
    ("data/child_protection_arabic_legal_llm/child_protection_law_legal_llm_001_025.json",
     "child_protection", "law"),
    ("data/protection_from_abuse_arabic_legal_llm/protection_from_abuse_law_legal_llm_001_017.json",
     "protection_from_abuse", "law"),
    ("data/associations_ngo_arabic_legal_llm/associations_ngo_law_legal_llm_001_044.json",
     "associations_ngo", "law"),
    ("data/audiovisual_media_arabic_legal_llm/audiovisual_media_law_legal_llm_001_025.json",
     "audiovisual_media", "law"),
    ("data/sports_arabic_legal_llm/sports_law_legal_llm_001_097.json",
     "sports", "law"),
    ("data/anti_smoking_arabic_legal_llm/anti_smoking_law_legal_llm_001_020.json",
     "anti_smoking", "law"),
    ("data/weapons_ammunition_arabic_legal_llm/weapons_ammunition_law_legal_llm_001_063.json",
     "weapons_ammunition", "law"),
    ("data/prison_detention_arabic_legal_llm/prison_detention_law_legal_llm_001_031.json",
     "prison_detention", "law"),
    ("data/civil_defense_arabic_legal_llm/civil_defense_law_legal_llm_001_036.json",
     "civil_defense", "law"),
    ("data/cooperative_societies_arabic_legal_llm/cooperative_societies_law_legal_llm_001_044.json",
     "cooperative_societies", "law"),
    ("data/building_code_arabic_legal_llm/building_code_law_legal_llm_001_016.json",
     "building_code", "law"),
    ("data/product_safety_arabic_legal_llm/product_safety_law_legal_llm_001_037.json",
     "product_safety", "law"),
    ("data/standards_quality_arabic_legal_llm/standards_quality_law_legal_llm_001_024.json",
     "standards_quality", "law"),
    ("data/disability_rights_arabic_legal_llm/disability_rights_law_legal_llm_001_033.json",
     "disability_rights", "law"),
    ("data/tourism_arabic_legal_llm/tourism_law_legal_llm_001_019.json",
     "tourism", "law"),
    ("data/tourism_travel_services_reg_arabic_legal_llm/tourism_travel_services_reg_legal_llm_001_032.json",
     "tourism_travel_services", "regulation"),
    ("data/hospitality_mgmt_reg_arabic_legal_llm/hospitality_mgmt_reg_legal_llm_001_024.json",
     "hospitality_mgmt", "regulation"),
    ("data/hospitality_facility_reg_arabic_legal_llm/hospitality_facility_reg_legal_llm_001_036.json",
     "hospitality_facility", "regulation"),
    ("data/tourist_visa_reg_arabic_legal_llm/tourist_visa_reg_legal_llm_001_013.json",
     "tourist_visa", "regulation"),
    ("data/environmental_noise_reg_arabic_legal_llm/environmental_noise_reg_legal_llm_001_013.json",
     "environmental_noise", "regulation"),
    ("data/environmental_protected_areas_reg_arabic_legal_llm/environmental_protected_areas_reg_legal_llm_001_011.json",
     "environmental_protected_areas", "regulation"),
    ("data/environmental_emergency_response_reg_arabic_legal_llm/environmental_emergency_response_reg_legal_llm_001_012.json",
     "environmental_emergency_response", "regulation"),
    ("data/product_safety_regulation_arabic_legal_llm/product_safety_regulation_legal_llm_001_075.json",
     "product_safety", "regulation"),
    ("data/handicrafts_law_arabic_legal_llm/handicrafts_law_legal_llm_001_018.json",
     "handicrafts_law", "law"),
    ("data/medical_devices_law_arabic_legal_llm/medical_devices_law_legal_llm_001_049.json",
     "medical_devices_law", "law"),
    ("data/museums_authority_licensing_regulation_arabic_legal_llm/museums_authority_licensing_regulation_legal_llm_001_023.json",
     "museums_authority_licensing_regulation", "regulation"),
    ("data/arabian_horse_regulation_arabic_legal_llm/arabian_horse_regulation_legal_llm_001_009.json",
     "arabian_horse_regulation", "regulation"),
    ("data/classification_societies_authorisation_regulation_arabic_legal_llm/classification_societies_authorisation_regulation_legal_llm_001_012.json",
     "classification_societies_authorisation_regulation", "regulation"),
    ("data/community_funds_rules_arabic_legal_llm/community_funds_rules_legal_llm_001_010.json",
     "community_funds_rules", "rules"),
    ("data/competencies_contractors_program_rules_arabic_legal_llm/competencies_contractors_program_rules_legal_llm_001_005.json",
     "competencies_contractors_program_rules", "rules"),
    ("data/conformity_models_general_regulation_arabic_legal_llm/conformity_models_general_regulation_legal_llm_001_007.json",
     "conformity_models_general_regulation", "regulation"),
    ("data/continuing_professional_education_rules_arabic_legal_llm/continuing_professional_education_rules_legal_llm_001_009.json",
     "continuing_professional_education_rules", "rules"),
    ("data/dry_gas_tankers_technical_regulation_arabic_legal_llm/dry_gas_tankers_technical_regulation_legal_llm_001_011.json",
     "dry_gas_tankers_technical_regulation", "regulation"),
    ("data/electromagnetic_compatibility_technical_regulation_arabic_legal_llm/electromagnetic_compatibility_technical_regulation_legal_llm_001_012.json",
     "electromagnetic_compatibility_technical_regulation", "regulation"),
    ("data/environmental_rehabilitation_contaminated_sites_regulation_arabic_legal_llm/environmental_rehabilitation_contaminated_sites_regulation_legal_llm_001_008.json",
     "environmental_rehabilitation_contaminated_sites_regulation", "regulation"),
    ("data/explosive_atmospheres_equipment_technical_regulation_arabic_legal_llm/explosive_atmospheres_equipment_technical_regulation_legal_llm_001_012.json",
     "explosive_atmospheres_equipment_technical_regulation", "regulation"),
    ("data/foreign_investment_securities_rules_arabic_legal_llm/foreign_investment_securities_rules_legal_llm_001_011.json",
     "foreign_investment_securities_rules", "rules"),
    ("data/government_allocation_objections_committee_rules_arabic_legal_llm/government_allocation_objections_committee_rules_legal_llm_001_009.json",
     "government_allocation_objections_committee_rules", "rules"),
    ("data/hazardous_substances_electrical_equipment_regulation_arabic_legal_llm/hazardous_substances_electrical_equipment_regulation_legal_llm_001_011.json",
     "hazardous_substances_electrical_equipment_regulation", "regulation"),
    ("data/jewellery_accessories_technical_regulation_arabic_legal_llm/jewellery_accessories_technical_regulation_legal_llm_001_012.json",
     "jewellery_accessories_technical_regulation", "regulation"),
    ("data/kacaah_horse_disposal_regulation_arabic_legal_llm/kacaah_horse_disposal_regulation_legal_llm_001_012.json",
     "kacaah_horse_disposal_regulation", "regulation"),
    ("data/king_abdulaziz_reserve_beekeeping_controls_arabic_legal_llm/king_abdulaziz_reserve_beekeeping_controls_legal_llm_001_009.json",
     "king_abdulaziz_reserve_beekeeping_controls", "rules"),
    ("data/king_abdulaziz_reserve_tourism_permits_controls_arabic_legal_llm/king_abdulaziz_reserve_tourism_permits_controls_legal_llm_001_010.json",
     "king_abdulaziz_reserve_tourism_permits_controls", "rules"),
    ("data/land_customs_storage_fees_controls_arabic_legal_llm/land_customs_storage_fees_controls_legal_llm_001_011.json",
     "land_customs_storage_fees_controls", "rules"),
    ("data/leather_products_technical_regulation_arabic_legal_llm/leather_products_technical_regulation_legal_llm_001_012.json",
     "leather_products_technical_regulation", "regulation"),
    ("data/makkah_holy_sites_transport_center_regulation_arabic_legal_llm/makkah_holy_sites_transport_center_regulation_legal_llm_001_010.json",
     "makkah_holy_sites_transport_center_regulation", "regulation"),
    ("data/marina_bunkering_controls_arabic_legal_llm/marina_bunkering_controls_legal_llm_001_010.json",
     "marina_bunkering_controls", "rules"),
    ("data/maritime_education_training_accreditation_regulation_arabic_legal_llm/maritime_education_training_accreditation_regulation_legal_llm_001_011.json",
     "maritime_education_training_accreditation_regulation", "regulation"),
    ("data/maritime_service_record_regulation_arabic_legal_llm/maritime_service_record_regulation_legal_llm_001_012.json",
     "maritime_service_record_regulation", "regulation"),
    ("data/maritime_tour_operator_regulation_arabic_legal_llm/maritime_tour_operator_regulation_legal_llm_001_010.json",
     "maritime_tour_operator_regulation", "regulation"),
    ("data/maritime_tourism_agent_controls_arabic_legal_llm/maritime_tourism_agent_controls_legal_llm_001_010.json",
     "maritime_tourism_agent_controls", "rules"),
    ("data/maritime_tourism_craft_classification_controls_arabic_legal_llm/maritime_tourism_craft_classification_controls_legal_llm_001_005.json",
     "maritime_tourism_craft_classification_controls", "rules"),
    ("data/medical_referrals_center_statute_arabic_legal_llm/medical_referrals_center_statute_legal_llm_001_011.json",
     "medical_referrals_center_statute", "statute"),
    ("data/ozone_depleting_substances_regulation_arabic_legal_llm/ozone_depleting_substances_regulation_legal_llm_001_009.json",
     "ozone_depleting_substances_regulation", "regulation"),
    ("data/paper_cardboard_technical_regulation_arabic_legal_llm/paper_cardboard_technical_regulation_legal_llm_001_011.json",
     "paper_cardboard_technical_regulation", "regulation"),
    ("data/public_agencies_staff_provisions_rules_arabic_legal_llm/public_agencies_staff_provisions_rules_legal_llm_001_012.json",
     "public_agencies_staff_provisions_rules", "rules"),
    ("data/real_estate_consultancy_analytics_regulation_arabic_legal_llm/real_estate_consultancy_analytics_regulation_legal_llm_001_010.json",
     "real_estate_consultancy_analytics_regulation", "regulation"),
    ("data/real_estate_contributions_escrow_controls_arabic_legal_llm/real_estate_contributions_escrow_controls_legal_llm_001_007.json",
     "real_estate_contributions_escrow_controls", "rules"),
    ("data/real_estate_market_analysis_controls_arabic_legal_llm/real_estate_market_analysis_controls_legal_llm_001_006.json",
     "real_estate_market_analysis_controls", "rules"),
    ("data/returned_goods_customs_exemption_controls_arabic_legal_llm/returned_goods_customs_exemption_controls_legal_llm_001_008.json",
     "returned_goods_customs_exemption_controls", "rules"),
    ("data/riyadh_infrastructure_projects_compliance_controls_arabic_legal_llm/riyadh_infrastructure_projects_compliance_controls_legal_llm_001_010.json",
     "riyadh_infrastructure_projects_compliance_controls", "rules"),
    ("data/sarah_sudairi_womens_studies_center_statute_arabic_legal_llm/sarah_sudairi_womens_studies_center_statute_legal_llm_001_012.json",
     "sarah_sudairi_womens_studies_center_statute", "statute"),
    ("data/sedimentary_shelf_well_drilling_permits_controls_arabic_legal_llm/sedimentary_shelf_well_drilling_permits_controls_legal_llm_001_008.json",
     "sedimentary_shelf_well_drilling_permits_controls", "rules"),
    ("data/service_centers_fuel_stations_committee_rules_arabic_legal_llm/service_centers_fuel_stations_committee_rules_legal_llm_001_010.json",
     "service_centers_fuel_stations_committee_rules", "rules"),
    ("data/shareek_program_center_statute_arabic_legal_llm/shareek_program_center_statute_legal_llm_001_011.json",
     "shareek_program_center_statute", "statute"),
    ("data/special_use_vehicle_equipment_technical_regulation_arabic_legal_llm/special_use_vehicle_equipment_technical_regulation_legal_llm_001_011.json",
     "special_use_vehicle_equipment_technical_regulation", "regulation"),
    ("data/superyacht_chartering_controls_arabic_legal_llm/superyacht_chartering_controls_legal_llm_001_011.json",
     "superyacht_chartering_controls", "rules"),
    ("data/tobacco_products_submission_fees_regulation_arabic_legal_llm/tobacco_products_submission_fees_regulation_legal_llm_001_005.json",
     "tobacco_products_submission_fees_regulation", "regulation"),
    ("data/tourist_destinations_regulation_arabic_legal_llm/tourist_destinations_regulation_legal_llm_001_008.json",
     "tourist_destinations_regulation", "regulation"),
    ("data/two_holy_mosques_religious_affairs_presidency_statute_arabic_legal_llm/two_holy_mosques_religious_affairs_presidency_statute_legal_llm_001_012.json",
     "two_holy_mosques_religious_affairs_presidency_statute", "statute"),
    ("data/unesco_national_commission_statute_arabic_legal_llm/unesco_national_commission_statute_legal_llm_001_013.json",
     "unesco_national_commission_statute", "statute"),
    ("data/used_imported_vehicles_technical_regulation_arabic_legal_llm/used_imported_vehicles_technical_regulation_legal_llm_001_011.json",
     "used_imported_vehicles_technical_regulation", "regulation"),
    ("data/vegetation_cover_desertification_regulation_arabic_legal_llm/vegetation_cover_desertification_regulation_legal_llm_001_011.json",
     "vegetation_cover_desertification_regulation", "regulation"),
    ("data/wheat_seasonal_fodder_cultivation_controls_arabic_legal_llm/wheat_seasonal_fodder_cultivation_controls_legal_llm_001_006.json",
     "wheat_seasonal_fodder_cultivation_controls", "rules"),
    ("data/zakat_tax_dispute_settlement_committees_rules_arabic_legal_llm/zakat_tax_dispute_settlement_committees_rules_legal_llm_001_009.json",
     "zakat_tax_dispute_settlement_committees_rules", "rules"),
    ("data/agricultural_development_fund_law_arabic_legal_llm/agricultural_development_fund_law_legal_llm_001_016.json",
     "agricultural_development_fund_law", "law"),
    ("data/baha_strategic_office_statute_arabic_legal_llm/baha_strategic_office_statute_legal_llm_001_013.json",
     "baha_strategic_office_statute", "statute"),
    ("data/crafts_professions_heads_elections_regulation_arabic_legal_llm/crafts_professions_heads_elections_regulation_legal_llm_001_013.json",
     "crafts_professions_heads_elections_regulation", "regulation"),
    ("data/cruise_ships_controls_arabic_legal_llm/cruise_ships_controls_legal_llm_001_014.json",
     "cruise_ships_controls", "rules"),
    ("data/cultural_development_fund_law_arabic_legal_llm/cultural_development_fund_law_legal_llm_001_015.json",
     "cultural_development_fund_law", "law"),
    ("data/digital_content_council_statute_arabic_legal_llm/digital_content_council_statute_legal_llm_001_014.json",
     "digital_content_council_statute", "statute"),
    ("data/energy_allocation_regulation_arabic_legal_llm/energy_allocation_regulation_legal_llm_001_015.json",
     "energy_allocation_regulation", "regulation"),
    ("data/enterprise_size_measurement_rules_arabic_legal_llm/enterprise_size_measurement_rules_legal_llm_001_013.json",
     "enterprise_size_measurement_rules", "rules"),
    ("data/final_clearing_collateral_regulation_arabic_legal_llm/final_clearing_collateral_regulation_legal_llm_001_015.json",
     "final_clearing_collateral_regulation", "regulation"),
    ("data/food_security_authority_statute_arabic_legal_llm/food_security_authority_statute_legal_llm_001_016.json",
     "food_security_authority_statute", "statute"),
    ("data/general_irrigation_corporation_statute_arabic_legal_llm/general_irrigation_corporation_statute_legal_llm_001_016.json",
     "general_irrigation_corporation_statute", "statute"),
    ("data/general_roads_authority_statute_arabic_legal_llm/general_roads_authority_statute_legal_llm_001_014.json",
     "general_roads_authority_statute", "statute"),
    ("data/government_property_allocation_transfer_controls_arabic_legal_llm/government_property_allocation_transfer_controls_legal_llm_001_013.json",
     "government_property_allocation_transfer_controls", "rules"),
    ("data/government_resource_systems_center_statute_arabic_legal_llm/government_resource_systems_center_statute_legal_llm_001_015.json",
     "government_resource_systems_center_statute", "statute"),
    ("data/high_industrial_security_authority_statute_arabic_legal_llm/high_industrial_security_authority_statute_legal_llm_001_016.json",
     "high_industrial_security_authority_statute", "statute"),
    ("data/industrial_mining_consultancy_rules_arabic_legal_llm/industrial_mining_consultancy_rules_legal_llm_001_014.json",
     "industrial_mining_consultancy_rules", "rules"),
    ("data/jazan_strategic_office_statute_arabic_legal_llm/jazan_strategic_office_statute_legal_llm_001_013.json",
     "jazan_strategic_office_statute", "statute"),
    ("data/job_seeker_allowance_statute_arabic_legal_llm/job_seeker_allowance_statute_legal_llm_001_013.json",
     "job_seeker_allowance_statute", "statute"),
    ("data/jouf_strategic_office_statute_arabic_legal_llm/jouf_strategic_office_statute_legal_llm_001_013.json",
     "jouf_strategic_office_statute", "statute"),
    ("data/kacare_statute_arabic_legal_llm/kacare_statute_legal_llm_001_015.json",
     "kacare_statute", "statute"),
    ("data/kacst_statute_arabic_legal_llm/kacst_statute_legal_llm_001_014.json",
     "kacst_statute", "statute"),
    ("data/king_abdullah_language_planning_center_statute_arabic_legal_llm/king_abdullah_language_planning_center_statute_legal_llm_001_015.json",
     "king_abdullah_language_planning_center_statute", "statute"),
    ("data/marina_design_operation_controls_arabic_legal_llm/marina_design_operation_controls_legal_llm_001_013.json",
     "marina_design_operation_controls", "rules"),
    ("data/maritime_travel_ticket_sales_regulation_arabic_legal_llm/maritime_travel_ticket_sales_regulation_legal_llm_001_016.json",
     "maritime_travel_ticket_sales_regulation", "regulation"),
    ("data/media_regulation_authority_statute_arabic_legal_llm/media_regulation_authority_statute_legal_llm_001_016.json",
     "media_regulation_authority_statute", "statute"),
    ("data/municipal_licensing_procedures_regulation_arabic_legal_llm/municipal_licensing_procedures_regulation_legal_llm_001_016.json",
     "municipal_licensing_procedures_regulation", "regulation"),
    ("data/national_curriculum_center_statute_arabic_legal_llm/national_curriculum_center_statute_legal_llm_001_015.json",
     "national_curriculum_center_statute", "statute"),
    ("data/national_health_research_institute_statute_arabic_legal_llm/national_health_research_institute_statute_legal_llm_001_015.json",
     "national_health_research_institute_statute", "statute"),
    ("data/national_inspection_control_center_statute_arabic_legal_llm/national_inspection_control_center_statute_legal_llm_001_015.json",
     "national_inspection_control_center_statute", "statute"),
    ("data/national_transport_safety_center_statute_arabic_legal_llm/national_transport_safety_center_statute_legal_llm_001_014.json",
     "national_transport_safety_center_statute", "statute"),
    ("data/nonprofit_beneficial_owner_rules_arabic_legal_llm/nonprofit_beneficial_owner_rules_legal_llm_001_013.json",
     "nonprofit_beneficial_owner_rules", "rules"),
    ("data/nonprofit_sector_development_center_statute_arabic_legal_llm/nonprofit_sector_development_center_statute_legal_llm_001_015.json",
     "nonprofit_sector_development_center_statute", "statute"),
    ("data/northern_borders_strategic_office_statute_arabic_legal_llm/northern_borders_strategic_office_statute_legal_llm_001_013.json",
     "northern_borders_strategic_office_statute", "statute"),
    ("data/occupational_safety_health_council_statute_arabic_legal_llm/occupational_safety_health_council_statute_legal_llm_001_013.json",
     "occupational_safety_health_council_statute", "statute"),
    ("data/palms_dates_center_statute_arabic_legal_llm/palms_dates_center_statute_legal_llm_001_013.json",
     "palms_dates_center_statute", "statute"),
    ("data/prince_mohammed_bin_salman_park_statute_arabic_legal_llm/prince_mohammed_bin_salman_park_statute_legal_llm_001_015.json",
     "prince_mohammed_bin_salman_park_statute", "statute"),
    ("data/private_entity_client_data_transfer_regulation_arabic_legal_llm/private_entity_client_data_transfer_regulation_legal_llm_001_013.json",
     "private_entity_client_data_transfer_regulation", "regulation"),
    ("data/public_health_authority_statute_arabic_legal_llm/public_health_authority_statute_legal_llm_001_014.json",
     "public_health_authority_statute", "statute"),
    ("data/public_utility_market_facilities_controls_arabic_legal_llm/public_utility_market_facilities_controls_legal_llm_001_015.json",
     "public_utility_market_facilities_controls", "rules"),
    ("data/rdi_authority_statute_arabic_legal_llm/rdi_authority_statute_legal_llm_001_015.json",
     "rdi_authority_statute", "statute"),
    ("data/real_estate_transaction_tax_regulation_arabic_legal_llm/real_estate_transaction_tax_regulation_legal_llm_001_015.json",
     "real_estate_transaction_tax_regulation", "regulation"),
    ("data/red_crescent_emblem_law_arabic_legal_llm/red_crescent_emblem_law_legal_llm_001_015.json",
     "red_crescent_emblem_law", "law"),
    ("data/red_sea_coral_turtles_authority_statute_arabic_legal_llm/red_sea_coral_turtles_authority_statute_legal_llm_001_016.json",
     "red_sea_coral_turtles_authority_statute", "statute"),
    ("data/regional_headquarters_tax_rules_arabic_legal_llm/regional_headquarters_tax_rules_legal_llm_001_016.json",
     "regional_headquarters_tax_rules", "rules"),
    ("data/royal_institute_traditional_arts_statute_arabic_legal_llm/royal_institute_traditional_arts_statute_legal_llm_001_016.json",
     "royal_institute_traditional_arts_statute", "statute"),
    ("data/safe_manning_regulation_arabic_legal_llm/safe_manning_regulation_legal_llm_001_016.json",
     "safe_manning_regulation", "regulation"),
    ("data/saudi_auditors_accountants_authority_statute_arabic_legal_llm/saudi_auditors_accountants_authority_statute_legal_llm_001_014.json",
     "saudi_auditors_accountants_authority_statute", "statute"),
    ("data/saudi_press_agency_statute_arabic_legal_llm/saudi_press_agency_statute_legal_llm_001_016.json",
     "saudi_press_agency_statute", "statute"),
    ("data/saudi_red_sea_authority_statute_arabic_legal_llm/saudi_red_sea_authority_statute_legal_llm_001_013.json",
     "saudi_red_sea_authority_statute", "statute"),
    ("data/saudi_space_agency_statute_arabic_legal_llm/saudi_space_agency_statute_legal_llm_001_013.json",
     "saudi_space_agency_statute", "statute"),
    ("data/saudi_tourism_authority_statute_arabic_legal_llm/saudi_tourism_authority_statute_legal_llm_001_015.json",
     "saudi_tourism_authority_statute", "statute"),
    ("data/saudi_water_authority_statute_arabic_legal_llm/saudi_water_authority_statute_legal_llm_001_015.json",
     "saudi_water_authority_statute", "statute"),
    ("data/ship_safety_management_regulation_arabic_legal_llm/ship_safety_management_regulation_legal_llm_001_014.json",
     "ship_safety_management_regulation", "regulation"),
    ("data/sme_bank_law_arabic_legal_llm/sme_bank_law_legal_llm_001_015.json",
     "sme_bank_law", "law"),
    ("data/state_property_authority_statute_arabic_legal_llm/state_property_authority_statute_legal_llm_001_016.json",
     "state_property_authority_statute", "statute"),
    ("data/two_holy_mosques_authority_statute_arabic_legal_llm/two_holy_mosques_authority_statute_legal_llm_001_016.json",
     "two_holy_mosques_authority_statute", "statute"),
    ("data/visiting_yachts_controls_arabic_legal_llm/visiting_yachts_controls_legal_llm_001_013.json",
     "visiting_yachts_controls", "rules"),
    ("data/waqf_investment_portfolios_regulation_arabic_legal_llm/waqf_investment_portfolios_regulation_legal_llm_001_013.json",
     "waqf_investment_portfolios_regulation", "regulation"),
    ("data/white_land_fees_executive_regulation_arabic_legal_llm/white_land_fees_executive_regulation_legal_llm_001_016.json",
     "white_land_fees_executive_regulation", "regulation"),
    ("data/wildlife_trade_regulation_arabic_legal_llm/wildlife_trade_regulation_legal_llm_001_013.json",
     "wildlife_trade_regulation", "regulation"),
    ("data/zatca_statute_arabic_legal_llm/zatca_statute_legal_llm_001_016.json",
     "zatca_statute", "statute"),
    ("data/alula_royal_commission_violations_committees_rules_arabic_legal_llm/alula_royal_commission_violations_committees_rules_legal_llm_001_025.json",
     "alula_royal_commission_violations_committees_rules", "rules"),
    ("data/nonprofit_center_supervisory_bodies_relations_regulation_arabic_legal_llm/nonprofit_center_supervisory_bodies_relations_regulation_legal_llm_001_019.json",
     "nonprofit_center_supervisory_bodies_relations_regulation", "regulation"),
    ("data/saudi_yachts_regulation_arabic_legal_llm/saudi_yachts_regulation_legal_llm_001_019.json",
     "saudi_yachts_regulation", "regulation"),
    ("data/zakat_tax_accounting_services_rules_arabic_legal_llm/zakat_tax_accounting_services_rules_legal_llm_001_019.json",
     "zakat_tax_accounting_services_rules", "rules"),
    ("data/national_emergency_management_authority_statute_arabic_legal_llm/national_emergency_management_authority_statute_legal_llm_001_019.json",
     "national_emergency_management_authority_statute", "statute"),
    ("data/riyadh_biotechnology_center_statute_arabic_legal_llm/riyadh_biotechnology_center_statute_legal_llm_001_019.json",
     "riyadh_biotechnology_center_statute", "statute"),
    ("data/digital_government_authority_statute_arabic_legal_llm/digital_government_authority_statute_legal_llm_001_018.json",
     "digital_government_authority_statute", "statute"),
    ("data/real_estate_development_fund_law_arabic_legal_llm/real_estate_development_fund_law_legal_llm_001_018.json",
     "real_estate_development_fund_law", "law"),
    ("data/building_code_inspection_bodies_regulation_arabic_legal_llm/building_code_inspection_bodies_regulation_legal_llm_001_018.json",
     "building_code_inspection_bodies_regulation", "regulation"),
    ("data/accounting_services_rules_arabic_legal_llm/accounting_services_rules_legal_llm_001_018.json",
     "accounting_services_rules", "rules"),
    ("data/king_salman_arabic_language_academy_statute_arabic_legal_llm/king_salman_arabic_language_academy_statute_legal_llm_001_018.json",
     "king_salman_arabic_language_academy_statute", "statute"),
    ("data/biological_weapons_convention_regulation_arabic_legal_llm/biological_weapons_convention_regulation_legal_llm_001_018.json",
     "biological_weapons_convention_regulation", "regulation"),
    ("data/national_infrastructure_fund_law_arabic_legal_llm/national_infrastructure_fund_law_legal_llm_001_018.json",
     "national_infrastructure_fund_law", "law"),
    ("data/public_auction_sale_rules_arabic_legal_llm/public_auction_sale_rules_legal_llm_001_018.json",
     "public_auction_sale_rules", "rules"),
    ("data/riyadh_nonprofit_foundation_statute_arabic_legal_llm/riyadh_nonprofit_foundation_statute_legal_llm_001_018.json",
     "riyadh_nonprofit_foundation_statute", "statute"),
    ("data/state_property_allocation_recovery_controls_arabic_legal_llm/state_property_allocation_recovery_controls_legal_llm_001_018.json",
     "state_property_allocation_recovery_controls", "rules"),
    ("data/government_foreign_property_lease_controls_arabic_legal_llm/government_foreign_property_lease_controls_legal_llm_001_018.json",
     "government_foreign_property_lease_controls", "rules"),
    ("data/chemicals_management_regulation_arabic_legal_llm/chemicals_management_regulation_legal_llm_001_018.json",
     "chemicals_management_regulation", "regulation"),
    ("data/trustees_experts_fees_rules_arabic_legal_llm/trustees_experts_fees_rules_legal_llm_001_017.json",
     "trustees_experts_fees_rules", "rules"),
    ("data/metrology_calibration_regulation_arabic_legal_llm/metrology_calibration_regulation_legal_llm_001_017.json",
     "metrology_calibration_regulation", "regulation"),
    ("data/financial_academy_statute_arabic_legal_llm/financial_academy_statute_legal_llm_001_017.json",
     "financial_academy_statute", "statute"),
    ("data/accredited_valuers_fellowship_rules_arabic_legal_llm/accredited_valuers_fellowship_rules_legal_llm_001_017.json",
     "accredited_valuers_fellowship_rules", "rules"),
    ("data/national_institute_educational_professional_development_statute_arabic_legal_llm/national_institute_educational_professional_development_statute_legal_llm_001_017.json",
     "national_institute_educational_professional_development_statute", "statute"),
    ("data/hrdf_support_violations_regulation_arabic_legal_llm/hrdf_support_violations_regulation_legal_llm_001_017.json",
     "hrdf_support_violations_regulation", "regulation"),
    ("data/libraries_authority_licensing_regulation_arabic_legal_llm/libraries_authority_licensing_regulation_legal_llm_001_023.json",
     "libraries_authority_licensing_regulation", "regulation"),
    ("data/theater_performing_arts_authority_licensing_regulation_arabic_legal_llm/theater_performing_arts_authority_licensing_regulation_legal_llm_001_023.json",
     "theater_performing_arts_authority_licensing_regulation", "regulation"),
    ("data/tourist_guidance_regulation_arabic_legal_llm/tourist_guidance_regulation_legal_llm_001_019.json",
     "tourist_guidance_regulation", "regulation"),
    ("data/king_saud_university_statute_arabic_legal_llm/king_saud_university_statute_legal_llm_001_022.json",
     "king_saud_university_statute", "statute"),
    ("data/king_faisal_specialist_hospital_statute_arabic_legal_llm/king_faisal_specialist_hospital_statute_legal_llm_001_021.json",
     "king_faisal_specialist_hospital_statute", "statute"),
    ("data/king_khaled_eye_hospital_statute_arabic_legal_llm/king_khaled_eye_hospital_statute_legal_llm_001_021.json",
     "king_khaled_eye_hospital_statute", "statute"),
    ("data/state_property_acquisition_controls_arabic_legal_llm/state_property_acquisition_controls_legal_llm_001_022.json",
     "state_property_acquisition_controls", "rules"),
    ("data/rehabilitation_and_damage_compensation_rules_arabic_legal_llm/rehabilitation_and_damage_compensation_rules_legal_llm_001_022.json",
     "rehabilitation_and_damage_compensation_rules", "rules"),
    ("data/export_restriction_governance_statute_arabic_legal_llm/export_restriction_governance_statute_legal_llm_001_021.json",
     "export_restriction_governance_statute", "statute"),
    ("data/occupational_fitness_examinations_regulation_arabic_legal_llm/occupational_fitness_examinations_regulation_legal_llm_001_021.json",
     "occupational_fitness_examinations_regulation", "regulation"),
    ("data/municipal_professions_crafts_licensing_regulation_arabic_legal_llm/municipal_professions_crafts_licensing_regulation_legal_llm_001_020.json",
     "municipal_professions_crafts_licensing_regulation", "regulation"),
    ("data/antifouling_systems_regulation_arabic_legal_llm/antifouling_systems_regulation_legal_llm_001_020.json",
     "antifouling_systems_regulation", "regulation"),
    ("data/cma_auditors_registration_rules_arabic_legal_llm/cma_auditors_registration_rules_legal_llm_001_019.json",
     "cma_auditors_registration_rules", "rules"),
    ("data/national_risk_council_statute_arabic_legal_llm/national_risk_council_statute_legal_llm_001_019.json",
     "national_risk_council_statute", "statute"),
    ("data/public_utility_markets_general_rules_arabic_legal_llm/public_utility_markets_general_rules_legal_llm_001_019.json",
     "public_utility_markets_general_rules", "rules"),
    ("data/literature_publishing_translation_authority_statute_arabic_legal_llm/literature_publishing_translation_authority_statute_legal_llm_001_012.json",
     "literature_publishing_translation_authority_statute", "statute"),
    ("data/museums_authority_statute_arabic_legal_llm/museums_authority_statute_legal_llm_001_012.json",
     "museums_authority_statute", "statute"),
    ("data/heritage_authority_statute_arabic_legal_llm/heritage_authority_statute_legal_llm_001_012.json",
     "heritage_authority_statute", "statute"),
    ("data/film_authority_statute_arabic_legal_llm/film_authority_statute_legal_llm_001_012.json",
     "film_authority_statute", "statute"),
    ("data/libraries_authority_statute_arabic_legal_llm/libraries_authority_statute_legal_llm_001_012.json",
     "libraries_authority_statute", "statute"),
    ("data/architecture_design_authority_statute_arabic_legal_llm/architecture_design_authority_statute_legal_llm_001_012.json",
     "architecture_design_authority_statute", "statute"),
    ("data/music_authority_statute_arabic_legal_llm/music_authority_statute_legal_llm_001_012.json",
     "music_authority_statute", "statute"),
    ("data/theater_performing_arts_authority_statute_arabic_legal_llm/theater_performing_arts_authority_statute_legal_llm_001_012.json",
     "theater_performing_arts_authority_statute", "statute"),
    ("data/visual_arts_authority_statute_arabic_legal_llm/visual_arts_authority_statute_legal_llm_001_012.json",
     "visual_arts_authority_statute", "statute"),
    ("data/culinary_arts_authority_statute_arabic_legal_llm/culinary_arts_authority_statute_legal_llm_001_012.json",
     "culinary_arts_authority_statute", "statute"),
    ("data/fashion_authority_statute_arabic_legal_llm/fashion_authority_statute_legal_llm_001_012.json",
     "fashion_authority_statute", "statute"),
    ("data/vehicle_periodic_inspection_statute_arabic_legal_llm/vehicle_periodic_inspection_statute_legal_llm_001_016.json",
     "vehicle_periodic_inspection_statute", "statute"),
    ("data/public_transport_users_rights_regulation_arabic_legal_llm/public_transport_users_rights_regulation_legal_llm_001_021.json",
     "public_transport_users_rights_regulation", "regulation"),
    ("data/sez_cloud_computing_regulation_arabic_legal_llm/sez_cloud_computing_regulation_legal_llm_001_031.json",
     "sez_cloud_computing_regulation", "regulation"),
    ("data/heritage_authority_licensing_regulation_arabic_legal_llm/heritage_authority_licensing_regulation_legal_llm_001_023.json",
     "heritage_authority_licensing_regulation", "regulation"),
    ("data/literature_publishing_translation_authority_licensing_regulation_arabic_legal_llm/literature_publishing_translation_authority_licensing_regulation_legal_llm_001_023.json",
     "literature_publishing_translation_authority_licensing_regulation", "regulation"),
    ("data/film_authority_licensing_regulation_arabic_legal_llm/film_authority_licensing_regulation_legal_llm_001_023.json",
     "film_authority_licensing_regulation", "regulation"),
    ("data/fashion_authority_licensing_regulation_arabic_legal_llm/fashion_authority_licensing_regulation_legal_llm_001_023.json",
     "fashion_authority_licensing_regulation", "regulation"),
    ("data/music_authority_licensing_regulation_arabic_legal_llm/music_authority_licensing_regulation_legal_llm_001_023.json",
     "music_authority_licensing_regulation", "regulation"),
    ("data/culinary_arts_authority_licensing_regulation_arabic_legal_llm/culinary_arts_authority_licensing_regulation_legal_llm_001_023.json",
     "culinary_arts_authority_licensing_regulation", "regulation"),
    ("data/architecture_design_authority_licensing_regulation_arabic_legal_llm/architecture_design_authority_licensing_regulation_legal_llm_001_023.json",
     "architecture_design_authority_licensing_regulation", "regulation"),
    ("data/visual_arts_authority_licensing_regulation_arabic_legal_llm/visual_arts_authority_licensing_regulation_legal_llm_001_023.json",
     "visual_arts_authority_licensing_regulation", "regulation"),
    ("data/tourism_consultancy_regulation_arabic_legal_llm/tourism_consultancy_regulation_legal_llm_001_023.json",
     "tourism_consultancy_regulation", "regulation"),
    ("data/tourism_activity_inspection_regulation_arabic_legal_llm/tourism_activity_inspection_regulation_legal_llm_001_023.json",
     "tourism_activity_inspection_regulation", "regulation"),
    ("data/duty_free_markets_rules_arabic_legal_llm/duty_free_markets_rules_legal_llm_001_023.json",
     "duty_free_markets_rules", "rules"),
    ("data/driving_schools_regulation_arabic_legal_llm/driving_schools_regulation_legal_llm_001_023.json",
     "driving_schools_regulation", "regulation"),
    ("data/railway_violations_committee_rules_arabic_legal_llm/railway_violations_committee_rules_legal_llm_001_024.json",
     "railway_violations_committee_rules", "rules"),
    ("data/public_transport_users_rights_mechanism_arabic_legal_llm/public_transport_users_rights_mechanism_legal_llm_001_076.json",
     "public_transport_users_rights_mechanism", "rules"),
    ("data/gcc_pesticides_regulation_arabic_legal_llm/gcc_pesticides_regulation_legal_llm_001_051.json",
     "gcc_pesticides_regulation", "regulation"),
    ("data/military_industries_rnd_regulation_arabic_legal_llm/military_industries_rnd_regulation_legal_llm_001_053.json",
     "military_industries_rnd_regulation", "regulation"),
    ("data/international_bus_transport_regulation_arabic_legal_llm/international_bus_transport_regulation_legal_llm_001_047.json",
     "international_bus_transport_regulation", "regulation"),
    ("data/vehicle_periodic_inspection_regulation_arabic_legal_llm/vehicle_periodic_inspection_regulation_legal_llm_001_045.json",
     "vehicle_periodic_inspection_regulation", "regulation"),
    ("data/health_specialties_membership_regulation_arabic_legal_llm/health_specialties_membership_regulation_legal_llm_001_041.json",
     "health_specialties_membership_regulation", "regulation"),
    ("data/disability_social_programs_regulation_arabic_legal_llm/disability_social_programs_regulation_legal_llm_001_040.json",
     "disability_social_programs_regulation", "regulation"),
    ("data/vehicle_damage_assessment_rules_arabic_legal_llm/vehicle_damage_assessment_rules_legal_llm_001_040.json",
     "vehicle_damage_assessment_rules", "rules"),
    ("data/tourist_accommodation_facilities_regulation_arabic_legal_llm/tourist_accommodation_facilities_regulation_legal_llm_001_040.json",
     "tourist_accommodation_facilities_regulation", "regulation"),
    ("data/ngo_council_regulation_arabic_legal_llm/ngo_council_regulation_legal_llm_001_039.json",
     "ngo_council_regulation", "regulation"),
    ("data/health_holding_company_statute_arabic_legal_llm/health_holding_company_statute_legal_llm_001_038.json",
     "health_holding_company_statute", "statute"),
    ("data/family_funds_rules_arabic_legal_llm/family_funds_rules_legal_llm_001_036.json",
     "family_funds_rules", "rules"),
    ("data/airports_economic_regulation_arabic_legal_llm/airports_economic_regulation_legal_llm_001_034.json",
     "airports_economic_regulation", "regulation"),
    ("data/valuation_profession_conduct_rules_arabic_legal_llm/valuation_profession_conduct_rules_legal_llm_001_034.json",
     "valuation_profession_conduct_rules", "rules"),
    ("data/nazara_works_regulation_arabic_legal_llm/nazara_works_regulation_legal_llm_001_032.json",
     "nazara_works_regulation", "regulation"),
    ("data/ballast_water_regulation_arabic_legal_llm/ballast_water_regulation_legal_llm_001_031.json",
     "ballast_water_regulation", "regulation"),
    ("data/sez_kaec_regulation_arabic_legal_llm/sez_kaec_regulation_legal_llm_001_035.json",
     "sez_kaec_regulation", "regulation"),
    ("data/sez_jazan_regulation_arabic_legal_llm/sez_jazan_regulation_legal_llm_001_034.json",
     "sez_jazan_regulation", "regulation"),
    ("data/sez_raskhair_regulation_arabic_legal_llm/sez_raskhair_regulation_legal_llm_001_034.json",
     "sez_raskhair_regulation", "regulation"),
    ("data/charitable_societies_council_regulation_arabic_legal_llm/charitable_societies_council_regulation_legal_llm_001_065.json",
     "charitable_societies_council_regulation", "regulation"),
    ("data/customs_procedures_controls_arabic_legal_llm/customs_procedures_controls_legal_llm_001_048.json",
     "customs_procedures_controls", "rules"),
    ("data/social_security_regulation_arabic_legal_llm/social_security_regulation_legal_llm_001_028.json",
     "social_security_regulation", "regulation"),
    ("data/revenue_sharing_rules_arabic_legal_llm/revenue_sharing_rules_legal_llm_001_031.json",
     "revenue_sharing_rules", "rules"),
    ("data/freight_broker_logistics_regulation_arabic_legal_llm/freight_broker_logistics_regulation_legal_llm_001_031.json",
     "freight_broker_logistics_regulation", "regulation"),
    ("data/property_ownership_committees_rules_arabic_legal_llm/property_ownership_committees_rules_legal_llm_001_030.json",
     "property_ownership_committees_rules", "rules"),
    ("data/disability_nongov_social_facilities_regulation_arabic_legal_llm/disability_nongov_social_facilities_regulation_legal_llm_001_030.json",
     "disability_nongov_social_facilities_regulation", "regulation"),
    ("data/free_zone_employees_treatment_rules_arabic_legal_llm/free_zone_employees_treatment_rules_legal_llm_001_028.json",
     "free_zone_employees_treatment_rules", "rules"),
    ("data/inspection_control_seizure_rules_arabic_legal_llm/inspection_control_seizure_rules_legal_llm_001_027.json",
     "inspection_control_seizure_rules", "rules"),
    ("data/ip_services_licensing_rules_arabic_legal_llm/ip_services_licensing_rules_legal_llm_001_025.json",
     "ip_services_licensing_rules", "rules"),
    ("data/deposit_zones_rules_arabic_legal_llm/deposit_zones_rules_legal_llm_001_025.json",
     "deposit_zones_rules", "rules"),
    ("data/air_transport_services_economic_regulation_arabic_legal_llm/air_transport_services_economic_regulation_legal_llm_001_025.json",
     "air_transport_services_economic_regulation", "regulation"),
    ("data/privatization_governing_rules_arabic_legal_llm/privatization_governing_rules_legal_llm_001_024.json",
     "privatization_governing_rules", "rules"),
    ("data/ground_handling_air_cargo_economic_regulation_arabic_legal_llm/ground_handling_air_cargo_economic_regulation_legal_llm_001_024.json",
     "ground_handling_air_cargo_economic_regulation", "regulation"),
    ("data/museums_regulation_arabic_legal_llm/museums_regulation_legal_llm_001_091.json",
     "museums_regulation", "regulation"),
    ("data/private_universities_regulation_arabic_legal_llm/private_universities_regulation_legal_llm_001_059.json",
     "private_universities_regulation", "regulation"),
    ("data/gcc_road_transport_law_arabic_legal_llm/gcc_road_transport_law_legal_llm_001_025.json",
     "gcc_road_transport_law", "law"),
    ("data/marpol_regulation_arabic_legal_llm/marpol_regulation_legal_llm_001_100.json",
     "marpol_regulation", "regulation"),
    ("data/securities_disputes_rules_arabic_legal_llm/securities_disputes_rules_legal_llm_001_084.json",
     "securities_disputes_rules", "rules"),
    ("data/state_realestate_disposal_regulation_arabic_legal_llm/state_realestate_disposal_regulation_legal_llm_001_074.json",
     "state_realestate_disposal_regulation", "regulation"),
    ("data/securities_depository_markets_regulation_arabic_legal_llm/securities_depository_markets_regulation_legal_llm_001_060.json",
     "securities_depository_markets_regulation", "regulation"),
    ("data/capital_adequacy_rules_arabic_legal_llm/capital_adequacy_rules_legal_llm_001_118.json",
     "capital_adequacy_rules", "rules"),
    ("data/mergers_acquisitions_regulation_arabic_legal_llm/mergers_acquisitions_regulation_legal_llm_001_053.json",
     "mergers_acquisitions_regulation", "regulation"),
    ("data/taxi_activity_regulation_arabic_legal_llm/taxi_activity_regulation_legal_llm_001_055.json",
     "taxi_activity_regulation", "regulation"),
    ("data/zakat_tax_customs_committees_rules_arabic_legal_llm/zakat_tax_customs_committees_rules_legal_llm_001_051.json",
     "zakat_tax_customs_committees_rules", "rules"),
    ("data/official_communications_records_regulation_arabic_legal_llm/official_communications_records_regulation_legal_llm_001_087.json",
     "official_communications_records_regulation", "regulation"),
    ("data/housing_support_regulation_arabic_legal_llm/housing_support_regulation_legal_llm_001_053.json",
     "housing_support_regulation", "regulation"),
    ("data/special_purpose_entities_rules_arabic_legal_llm/special_purpose_entities_rules_legal_llm_001_055.json",
     "special_purpose_entities_rules", "rules"),
    ("data/medical_devices_regulation_arabic_legal_llm/medical_devices_regulation_legal_llm_001_049.json",
     "medical_devices_regulation", "regulation"),
    ("data/financial_institutions_resolution_law_arabic_legal_llm/financial_institutions_resolution_law_legal_llm_001_038.json",
     "financial_institutions_resolution_law", "law"),
    ("data/trade_remedies_law_arabic_legal_llm/trade_remedies_law_legal_llm_001_037.json",
     "trade_remedies_law", "law"),
    ("data/trade_remedies_regulation_arabic_legal_llm/trade_remedies_regulation_legal_llm_001_064.json",
     "trade_remedies_regulation", "regulation"),
    ("data/financial_fraud_law_arabic_legal_llm/financial_fraud_law_legal_llm_001_011.json",
     "financial_fraud_law", "law"),
    ("data/state_property_lease_law_arabic_legal_llm/state_property_lease_law_legal_llm_001_031.json",
     "state_property_lease_law", "law"),
    ("data/state_property_lease_regulation_arabic_legal_llm/state_property_lease_regulation_legal_llm_001_079.json",
     "state_property_lease_regulation", "regulation"),
    ("data/job_discipline_law_arabic_legal_llm/job_discipline_law_legal_llm_001_025.json",
     "job_discipline_law", "law"),
    ("data/statistics_law_arabic_legal_llm/statistics_law_legal_llm_001_022.json",
     "statistics_law", "law"),
    ("data/anti_begging_law_arabic_legal_llm/anti_begging_law_legal_llm_001_010.json",
     "anti_begging_law", "law"),
    ("data/security_cameras_law_arabic_legal_llm/security_cameras_law_legal_llm_001_018.json",
     "security_cameras_law", "law"),
    ("data/antiquities_heritage_regulation_arabic_legal_llm/antiquities_heritage_regulation_legal_llm_001_113.json",
     "antiquities_heritage_regulation", "regulation"),
    ("data/meteorology_law_arabic_legal_llm/meteorology_law_legal_llm_001_020.json",
     "meteorology_law", "law"),
    ("data/handicrafts_regulation_arabic_legal_llm/handicrafts_regulation_legal_llm_001_014.json",
     "handicrafts_regulation", "regulation"),
    ("data/donations_collection_regulation_arabic_legal_llm/donations_collection_regulation_legal_llm_001_017.json",
     "donations_collection_regulation", "regulation"),
    ("data/falcon_center_statute_arabic_legal_llm/falcon_center_statute_legal_llm_001_017.json",
     "falcon_center_statute", "statute"),
    ("data/geographical_indications_regulation_arabic_legal_llm/geographical_indications_regulation_legal_llm_001_037.json",
     "geographical_indications_regulation", "regulation"),
    ("data/vacant_properties_fees_regulation_arabic_legal_llm/vacant_properties_fees_regulation_legal_llm_001_018.json",
     "vacant_properties_fees_regulation", "regulation"),
    ("data/waqf_investment_products_regulation_arabic_legal_llm/waqf_investment_products_regulation_legal_llm_001_037.json",
     "waqf_investment_products_regulation", "regulation"),
    ("data/insurance_disputes_committees_rules_arabic_legal_llm/insurance_disputes_committees_rules_legal_llm_001_046.json",
     "insurance_disputes_committees_rules", "rules"),
    ("data/entertainment_activities_law_arabic_legal_llm/entertainment_activities_law_legal_llm_001_016.json",
     "entertainment_activities_law", "law"),
    ("data/standards_quality_regulation_arabic_legal_llm/standards_quality_regulation_legal_llm_001_023.json",
     "standards_quality", "regulation"),
    ("data/disability_rights_regulation_arabic_legal_llm/disability_rights_regulation_legal_llm_001_045.json",
     "disability_rights", "regulation"),
    ("data/anti_smoking_regulation_arabic_legal_llm/anti_smoking_regulation_legal_llm_001_020.json",
     "anti_smoking", "regulation"),
    ("data/general_education_arabic_legal_llm/general_education_law_legal_llm_001_068.json",
     "general_education", "law"),
    ("data/credit_information_arabic_legal_llm/credit_information_law_legal_llm_001_017.json",
     "credit_information", "law"),
    ("data/real_estate_brokerage_arabic_legal_llm/real_estate_brokerage_law_legal_llm_001_024.json",
     "real_estate_brokerage", "law"),
    ("data/state_revenue_arabic_legal_llm/state_revenue_law_legal_llm_001_032.json",
     "state_revenue", "law"),
    ("data/etec_arabic_legal_llm/etec_law_legal_llm_001_018.json",
     "etec", "law"),
    ("data/einvoicing_regulation_arabic_legal_llm/einvoicing_regulation_legal_llm_001_007.json",
     "einvoicing", "regulation"),
    ("data/pdpl_cross_border_transfer_regulation_arabic_legal_llm/pdpl_cross_border_transfer_regulation_legal_llm_001_009.json",
     "pdpl", "cross_border_transfer_regulation"),
    ("data/sdaia_organizational_arrangements_arabic_legal_llm/sdaia_organizational_arrangements_legal_llm_001_016.json",
     "sdaia", "organizational_arrangements"),
    ("data/income_tax_arabic_legal_llm/income_tax_law_legal_llm_001_081.json",
     "income_tax", "law"),
    ("data/civil_service_arabic_legal_llm/civil_service_law_legal_llm_001_044.json",
     "civil_service", "law"),
    ("data/social_insurance_arabic_legal_llm/social_insurance_law_legal_llm_001_063.json",
     "social_insurance", "law"),
    ("data/social_insurance_legacy_arabic_legal_llm/social_insurance_legacy_law_legal_llm_001_071.json",
     "social_insurance_legacy", "law"),
    ("data/zakat_arabic_legal_llm/zakat_law_legal_llm_001_128.json",
     "zakat", "law"),
    ("data/patent_arabic_legal_llm/patent_law_legal_llm_001_066.json",
     "patent", "law"),
    ("data/patent_regulation_arabic_legal_llm/patent_regulation_legal_llm_001_067.json",
     "patent", "regulation"),
    ("data/customs_arabic_legal_llm/customs_law_legal_llm_001_188.json",
     "customs", "law"),
    ("data/customs_regulation_arabic_legal_llm/customs_regulation_legal_llm_001_036.json",
     "customs", "implementing_regulation"),
    ("data/anti_fraud_arabic_legal_llm/anti_fraud_law_legal_llm_001_030.json",
     "anti_fraud", "law"),
    ("data/finance_companies_arabic_legal_llm/finance_companies_law_legal_llm_001_041.json",
     "finance_companies", "law"),
    ("data/cooperative_health_insurance_arabic_legal_llm/cooperative_health_insurance_law_legal_llm_001_019.json",
     "cooperative_health_insurance", "law"),
    ("data/healthcare_professions_arabic_legal_llm/healthcare_professions_law_legal_llm_001_044.json",
     "healthcare_professions", "law"),
    ("data/finance_lease_arabic_legal_llm/finance_lease_law_legal_llm_001_028.json",
     "finance_lease", "law"),
    ("data/maritime_commercial_arabic_legal_llm/maritime_commercial_law_legal_llm_001_391.json",
     "maritime_commercial", "law"),
    ("data/gcc_anti_dumping_arabic_legal_llm/gcc_anti_dumping_law_legal_llm_001_017.json",
     "gcc_anti_dumping", "law"),
    ("data/accounting_auditing_arabic_legal_llm/accounting_auditing_law_legal_llm_001_022.json",
     "accounting_auditing", "law"),
    ("data/nazaha_arabic_legal_llm/nazaha_law_legal_llm_001_024.json",
     "nazaha", "law"),
    ("data/awqaf_arabic_legal_llm/awqaf_law_legal_llm_001_025.json",
     "awqaf", "law"),
    ("data/saudi_engineers_arabic_legal_llm/saudi_engineers_law_legal_llm_001_009.json",
     "saudi_engineers", "law"),
    ("data/municipal_councils_arabic_legal_llm/municipal_councils_law_legal_llm_001_069.json",
     "municipal_councils", "law"),
    ("data/press_arabic_legal_llm/press_law_legal_llm_001_049.json",
     "press", "law"),
    ("data/engineering_practice_arabic_legal_llm/engineering_practice_law_legal_llm_001_017.json",
     "engineering_practice", "law"),
    ("data/nationality_arabic_legal_llm/nationality_law_legal_llm_001_030.json",
     "nationality", "law"),
    ("data/residency_arabic_legal_llm/residency_law_legal_llm_001_069.json",
     "residency", "law"),
    ("data/civil_status_arabic_legal_llm/civil_status_law_legal_llm_001_096.json",
     "civil_status", "law"),
    ("data/food_arabic_legal_llm/food_law_legal_llm_001_044.json",
     "food", "law"),
    ("data/health_system_arabic_legal_llm/health_system_law_legal_llm_001_019.json",
     "health_system", "law"),
    ("data/domestic_labor_arabic_legal_llm/domestic_labor_regulation_legal_llm_001_033.json",
     "domestic_labor", "regulation"),
    ("data/travel_documents_arabic_legal_llm/travel_documents_law_legal_llm_001_016.json",
     "travel_documents", "law"),
    ("data/cybersecurity_authority_arabic_legal_llm/cybersecurity_authority_law_legal_llm_001_015.json",
     "cybersecurity_authority", "law"),
    ("data/cybersecurity_authority_enablers_arabic_legal_llm/cybersecurity_authority_enablers_legal_llm_001_007.json",
     "cybersecurity_authority", "enablers"),
    ("data/premium_residency_arabic_legal_llm/premium_residency_law_legal_llm_001_014.json",
     "premium_residency", "law"),
    ("data/travel_documents_regulation_arabic_legal_llm/travel_documents_regulation_legal_llm_001_053.json",
     "travel_documents", "regulation"),
    ("data/nationality_regulation_arabic_legal_llm/nationality_regulation_legal_llm_001_035.json",
     "nationality", "regulation"),
    ("data/health_system_regulation_arabic_legal_llm/health_system_regulation_legal_llm_001_010.json",
     "health_system", "regulation"),
    ("data/food_regulation_arabic_legal_llm/food_regulation_legal_llm_001_085.json",
     "food", "regulation"),
    ("data/electricity_arabic_legal_llm/electricity_law_legal_llm_001_023.json",
     "electricity", "law"),
    ("data/water_arabic_legal_llm/water_law_legal_llm_001_077.json",
     "water", "law"),
    ("data/vat_regulation_arabic_legal_llm/vat_regulation_legal_llm_001_082.json",
     "vat", "regulation"),
    ("data/income_tax_regulation_arabic_legal_llm/income_tax_regulation_legal_llm_001_074.json",
     "income_tax", "regulation"),
    ("data/agriculture_arabic_legal_llm/agriculture_law_legal_llm_001_037.json",
     "agriculture", "law"),

    ("data/trade_names_regulation_arabic_legal_llm/trade_names_regulation_legal_llm_001_019.json",
     "trade_names", "regulation"),
    ("data/commercial_agencies_regulation_arabic_legal_llm/commercial_agencies_regulation_legal_llm_001_049.json",
     "commercial_agencies", "regulation"),
    ("data/accounting_auditing_regulation_arabic_legal_llm/accounting_auditing_regulation_legal_llm_001_015.json",
     "accounting_auditing", "regulation"),
    ("data/commercial_register_regulation_arabic_legal_llm/commercial_register_regulation_legal_llm_001_021.json",
     "commercial_register", "regulation"),
    ("data/real_estate_brokerage_regulation_arabic_legal_llm/real_estate_brokerage_regulation_legal_llm_001_027.json",
     "real_estate_brokerage", "regulation"),
    ("data/foreign_ownership_regulation_arabic_legal_llm/foreign_ownership_regulation_legal_llm_001_015.json",
     "foreign_ownership", "regulation"),
    ("data/anti_fraud_regulation_arabic_legal_llm/anti_fraud_regulation_legal_llm_001_019.json",
     "anti_fraud", "regulation"),
    ("data/rett_regulation_arabic_legal_llm/rett_regulation_legal_llm_001_015.json",
     "rett", "regulation"),
    ("data/anti_narcotics_regulation_arabic_legal_llm/anti_narcotics_regulation_legal_llm_001_040.json",
     "anti_narcotics", "regulation"),
    ("data/anti_concealment_regulation_arabic_legal_llm/anti_concealment_regulation_legal_llm_001_018.json",
     "anti_concealment", "regulation"),
    ("data/privatization_regulation_arabic_legal_llm/privatization_regulation_legal_llm_001_169.json",
     "privatization", "regulation"),
    ("data/chambers_of_commerce_regulation_arabic_legal_llm/chambers_of_commerce_regulation_legal_llm_001_063.json",
     "chambers_of_commerce", "regulation"),
    ("data/state_revenue_regulation_arabic_legal_llm/state_revenue_regulation_legal_llm_001_065.json",
     "state_revenue", "regulation"),
    ("data/weapons_ammunition_regulation_arabic_legal_llm/weapons_ammunition_regulation_legal_llm_001_019.json",
     "weapons_ammunition", "regulation"),
    ("data/engineering_practice_regulation_arabic_legal_llm/engineering_practice_regulation_legal_llm_001_018.json",
     "engineering_practice", "regulation"),
    ("data/allegiance_commission_regulation_arabic_legal_llm/allegiance_commission_regulation_legal_llm_001_018.json",
     "allegiance_commission", "regulation"),
    ("data/social_insurance_regulation_arabic_legal_llm/social_insurance_regulation_legal_llm_001_107.json",
     "social_insurance", "regulation"),
    ("data/saudi_engineers_regulation_arabic_legal_llm/saudi_engineers_regulation_legal_llm_001_032.json",
     "saudi_engineers", "regulation"),
    ("data/child_protection_regulation_arabic_legal_llm/child_protection_regulation_legal_llm_001_025.json",
     "child_protection", "regulation"),
    ("data/whistleblower_regulation_arabic_legal_llm/whistleblower_regulation_legal_llm_001_012.json",
     "whistleblower", "regulation"),
    ("data/social_insurance_legacy_regulation_arabic_legal_llm/social_insurance_legacy_regulation_legal_llm_001_170.json",
     "social_insurance_legacy", "regulation"),
    ("data/protection_from_abuse_regulation_arabic_legal_llm/protection_from_abuse_regulation_legal_llm_001_014.json",
     "protection_from_abuse", "regulation"),
    ("data/healthcare_professions_regulation_arabic_legal_llm/healthcare_professions_regulation_legal_llm_001_030.json",
     "healthcare_professions", "regulation"),
    ("data/shura_council_internal_regulation_arabic_legal_llm/shura_council_internal_regulation_legal_llm_001_034.json",
     "shura_council", "regulation"),
    ("data/civil_service_regulation_arabic_legal_llm/civil_service_regulation_legal_llm_001_261.json",
     "civil_service", "regulation"),
    ("data/associations_ngo_regulation_arabic_legal_llm/associations_ngo_regulation_legal_llm_001_129.json",
     "associations_ngo", "regulation"),
    ("data/electronic_transactions_regulation_arabic_legal_llm/electronic_transactions_regulation_legal_llm_001_025.json",
     "electronic_transactions", "regulation"),
    ("data/electricity_regulation_arabic_legal_llm/electricity_regulation_legal_llm_001_092.json",
     "electricity", "regulation"),
    ("data/maritime_commercial_regulation_arabic_legal_llm/maritime_commercial_regulation_legal_llm_001_049.json",
     "maritime_commercial", "regulation"),
    ("data/agriculture_regulation_arabic_legal_llm/agriculture_regulation_legal_llm_001_271.json",
     "agriculture", "regulation"),
    ("data/civil_defense_regulation_arabic_legal_llm/civil_defense_regulation_legal_llm_001_021.json",
     "civil_defense", "regulation"),
    ("data/premium_residency_regulation_arabic_legal_llm/premium_residency_regulation_legal_llm_001_013.json",
     "premium_residency", "regulation"),
    ("data/water_regulation_arabic_legal_llm/water_regulation_legal_llm_001_0156.json",
     "water", "regulation"),
    ("data/press_regulation_arabic_legal_llm/press_regulation_legal_llm_001_099.json",
     "press", "regulation"),
    ("data/building_code_regulation_arabic_legal_llm/building_code_regulation_legal_llm_001_030.json",
     "building_code", "regulation"),
    ("data/telecommunications_regulation_arabic_legal_llm/telecommunications_regulation_legal_llm_001_108.json",
     "telecommunications", "regulation"),
    ("data/credit_information_regulation_arabic_legal_llm/credit_information_regulation_legal_llm_001_055.json",
     "credit_information", "regulation"),
    ("data/payment_systems_regulation_arabic_legal_llm/payment_systems_regulation_legal_llm_001_133.json",
     "payment_systems", "regulation"),
    ("data/banking_control_regulation_arabic_legal_llm/banking_control_regulation_legal_llm_001_031.json",
     "banking_control", "regulation"),
    ("data/finance_companies_regulation_arabic_legal_llm/finance_companies_regulation_legal_llm_001_106.json",
     "finance_companies", "regulation"),
    ("data/finance_lease_regulation_arabic_legal_llm/finance_lease_regulation_legal_llm_001_032.json",
     "finance_lease", "regulation"),
    ("data/cooperative_societies_regulation_arabic_legal_llm/cooperative_societies_regulation_legal_llm_001_055.json",
     "cooperative_societies", "regulation"),
    ("data/bog_enforcement_law_arabic_legal_llm/bog_enforcement_law_legal_llm_001_037.json",
     "bog_enforcement", "law"),
    ("data/public_prosecution_law_arabic_legal_llm/public_prosecution_law_legal_llm_001_030.json",
     "public_prosecution", "law"),
    ("data/elderly_care_law_arabic_legal_llm/elderly_care_law_legal_llm_001_023.json",
     "elderly_care", "law"),
    ("data/elderly_care_regulation_arabic_legal_llm/elderly_care_regulation_legal_llm_001_008.json",
     "elderly_care", "regulation"),
    ("data/private_schools_regulation_arabic_legal_llm/private_schools_regulation_legal_llm_001_024.json",
     "private_schools", "regulation"),
    ("data/foreign_schools_regulation_arabic_legal_llm/foreign_schools_regulation_legal_llm_001_021.json",
     "foreign_schools", "regulation"),
    ("data/postal_law_arabic_legal_llm/postal_law_legal_llm_001_020.json",
     "postal", "law"),
    ("data/cma_corporate_governance_regulation_arabic_legal_llm/cma_corporate_governance_regulation_legal_llm_001_095.json",
     "cma_corporate_governance", "regulation"),
    ("data/tvtc_organizational_statute_arabic_legal_llm/tvtc_organizational_statute_legal_llm_001_013.json",
     "tvtc", "law"),
    ("data/waste_management_law_arabic_legal_llm/waste_management_law_legal_llm_001_038.json",
     "waste_management", "law"),
    ("data/fisheries_law_arabic_legal_llm/fisheries_law_legal_llm_001_013.json",
     "fisheries", "law"),
    ("data/debt_collection_regulation_arabic_legal_llm/debt_collection_regulation_legal_llm_001_011.json",
     "debt_collection", "regulation"),
    ("data/insurance_authority_statute_arabic_legal_llm/insurance_authority_statute_legal_llm_001_015.json",
     "insurance_authority", "law"),
    ("data/bnpl_regulation_arabic_legal_llm/bnpl_regulation_legal_llm_001_031.json",
     "bnpl", "regulation"),
    ("data/offplan_sale_law_arabic_legal_llm/offplan_sale_law_legal_llm_001_030.json",
     "offplan_sale", "law"),
    ("data/contractors_classification_law_arabic_legal_llm/contractors_classification_law_legal_llm_001_019.json",
     "contractors_classification", "law"),
    ("data/real_estate_contributions_law_arabic_legal_llm/real_estate_contributions_law_legal_llm_001_038.json",
     "real_estate_contributions", "law"),
    ("data/accredited_valuers_law_arabic_legal_llm/accredited_valuers_law_legal_llm_001_045.json",
     "accredited_valuers", "law"),
    ("data/white_land_fees_law_arabic_legal_llm/white_land_fees_law_legal_llm_001_015.json",
     "white_land_fees", "law"),
    ("data/frequency_spectrum_regulation_arabic_legal_llm/frequency_spectrum_regulation_legal_llm_001_015.json",
     "frequency_spectrum", "regulation"),
    ("data/mental_health_law_arabic_legal_llm/mental_health_law_legal_llm_001_030.json",
     "mental_health", "law"),
    ("data/organ_donation_law_arabic_legal_llm/organ_donation_law_legal_llm_001_027.json",
     "organ_donation", "law"),
    ("data/private_healthcare_institutions_law_arabic_legal_llm/private_healthcare_institutions_law_legal_llm_001_035.json",
     "private_healthcare_institutions", "law"),
    ("data/high_risk_professions_regulation_arabic_legal_llm/high_risk_professions_regulation_legal_llm_001_019.json",
     "high_risk_professions", "regulation"),
    ("data/osh_service_providers_regulation_arabic_legal_llm/osh_service_providers_regulation_legal_llm_001_038.json",
     "osh_service_providers", "regulation"),
    ("data/rega_organizational_statute_arabic_legal_llm/rega_organizational_statute_legal_llm_001_016.json",
     "rega", "law"),

    # --- wave-6 batch (23 tracks from 268-track 8-sector gap scan) ---
    ("data/offplan_sale_implementing_regulation_arabic_legal_llm/offplan_sale_implementing_regulation_legal_llm_001_049.json",
     "offplan_sale_regulation", "regulation"),
    ("data/real_estate_finance_implementing_regulation_arabic_legal_llm/real_estate_finance_implementing_regulation_legal_llm_001_031.json",
     "real_estate_finance_regulation", "regulation"),
    ("data/real_estate_contributions_implementing_regulation_arabic_legal_llm/real_estate_contributions_implementing_regulation_legal_llm_001_040.json",
     "real_estate_contributions_regulation", "regulation"),
    ("data/landlord_tenant_relationship_regulation_arabic_legal_llm/landlord_tenant_relationship_regulation_legal_llm_001_012.json",
     "landlord_tenant", "regulation"),
    ("data/real_estate_marketing_advertising_regulation_arabic_legal_llm/real_estate_marketing_advertising_regulation_legal_llm_001_012.json",
     "real_estate_marketing", "regulation"),
    ("data/real_estate_auctions_regulation_arabic_legal_llm/real_estate_auctions_regulation_legal_llm_001_012.json",
     "real_estate_auctions", "regulation"),
    ("data/petroleum_petrochemical_materials_law_arabic_legal_llm/petroleum_petrochemical_materials_law_legal_llm_001_022.json",
     "petroleum_petrochemical", "law"),
    ("data/dry_gas_lpg_distribution_law_arabic_legal_llm/dry_gas_lpg_distribution_law_legal_llm_001_021.json",
     "dry_gas_lpg", "law"),
    ("data/energy_supplies_system_arabic_legal_llm/energy_supplies_system_legal_llm_001_012.json",
     "energy_supplies", "law"),
    ("data/mining_investment_implementing_regulation_arabic_legal_llm/mining_investment_implementing_regulation_legal_llm_001_166.json",
     "mining_investment_regulation", "regulation"),
    ("data/pharmaceutical_establishments_law_arabic_legal_llm/pharmaceutical_establishments_law_legal_llm_001_042.json",
     "pharmaceutical_establishments", "law"),
    ("data/seized_confiscated_funds_management_system_arabic_legal_llm/seized_confiscated_funds_management_system_legal_llm_001_015.json",
     "seized_confiscated_funds", "law"),
    ("data/nca_cybersecurity_violations_investigation_rules_arabic_legal_llm/nca_cybersecurity_violations_investigation_rules_legal_llm_001_009.json",
     "nca_investigation_rules", "regulation"),
    ("data/nca_cybersecurity_violations_reporting_rules_arabic_legal_llm/nca_cybersecurity_violations_reporting_rules_legal_llm_001_008.json",
     "nca_reporting_rules", "regulation"),
    ("data/cst_organizational_statute_arabic_legal_llm/cst_organizational_statute_legal_llm_001_019.json",
     "cst", "law"),
    ("data/railway_law_arabic_legal_llm/railway_law_legal_llm_001_050.json",
     "railway", "law"),
    ("data/railway_law_implementing_regulation_arabic_legal_llm/railway_law_implementing_regulation_legal_llm_001_091.json",
     "railway_regulation", "regulation"),
    ("data/road_transport_law_arabic_legal_llm/road_transport_law_legal_llm_001_034.json",
     "road_transport", "law"),
    ("data/gaca_organizational_statute_arabic_legal_llm/gaca_organizational_statute_legal_llm_001_015.json",
     "gaca", "law"),
    ("data/tga_organizational_statute_arabic_legal_llm/tga_organizational_statute_legal_llm_001_016.json",
     "tga", "law"),
    ("data/mawani_organizational_statute_arabic_legal_llm/mawani_organizational_statute_legal_llm_001_020.json",
     "mawani", "law"),
    ("data/hajj_umrah_external_pilgrims_law_arabic_legal_llm/hajj_umrah_external_pilgrims_law_legal_llm_001_024.json",
     "hajj_umrah_pilgrims", "law"),
    ("data/aviation_passenger_rights_regulation_arabic_legal_llm/aviation_passenger_rights_regulation_legal_llm_001_030.json",
     "aviation_passenger_rights", "regulation"),
]


def _law_title(envelope):
    # envelope title_ar is like "نظام الشركات — الطبقة العربية ..." -> take the part before the em dash
    t = envelope.get("title_ar", "")
    return t.split(" — ", 1)[0].strip() if " — " in t else t.strip()


def _text_of(rec):
    return rec.get("article_text_ar") or rec.get("official_text_ar") or ""


def _status_of(rec):
    return (rec.get("text_status")
            or rec.get("source_trust", {}).get("source_status")
            or rec.get("record_type")
            or "unspecified")


def build():
    rows = []
    counts = {}
    for rel, corpus, default_component in LAYERS:
        env = json.load(open(os.path.join(ROOT, rel), encoding="utf-8"))
        recs = env["records"] if isinstance(env, dict) and "records" in env else env
        law_title = _law_title(env) if isinstance(env, dict) else corpus
        n = 0
        for r in recs:
            rows.append({
                "record_id": r["record_id"],
                "corpus": corpus,
                "law_id": r.get("law_id"),
                "law_component": r.get("law_component", default_component),
                "law_title_ar": law_title,
                "article_number": r["article_number"],
                "llm_title_ar": r.get("llm_title_ar"),
                "retrieval_title_ar": r.get("retrieval_title_ar"),
                "article_path": r.get("article_path"),
                "keywords_ar": r.get("keywords_ar", []),
                "search_queries_ar": r.get("search_queries_ar", []),
                "text_ar": _text_of(r),
                "text_status": _status_of(r),
                "source_layer": os.path.basename(rel),
            })
            n += 1
        counts[os.path.basename(rel)] = n

    # stable order: corpus, law_component (law before regulation), article_number
    comp_rank = {"law": 0, "implementing_regulation": 1}
    rows.sort(key=lambda x: (x["corpus"], comp_rank.get(x["law_component"], 9), x["article_number"]))
    return rows, counts


def main():
    rows, counts = build()
    os.makedirs(OUT_DIR, exist_ok=True)
    with open(INDEX, "w", encoding="utf-8") as f:
        for r in rows:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")

    by_corpus = {}
    for r in rows:
        by_corpus[r["corpus"]] = by_corpus.get(r["corpus"], 0) + 1
    summary = {
        "index": "CORPUS_UNIFIED_LLM_RETRIEVAL_INDEX",
        "total_records": len(rows),
        "records_per_layer": counts,
        "records_per_corpus": by_corpus,
        "layers": [os.path.basename(rel) for rel, _, _ in LAYERS],
        "fields": ["record_id", "corpus", "law_id", "law_component", "law_title_ar",
                   "article_number", "llm_title_ar", "retrieval_title_ar", "article_path",
                   "keywords_ar", "search_queries_ar", "text_ar", "text_status", "source_layer"],
        "note": ("Flat retrieval index projected from the per-law LLM-ready enrichment layers. "
                 "No legal text altered, summarized, translated, or re-derived. Arabic governs."),
    }
    with open(SUMMARY, "w", encoding="utf-8") as f:
        json.dump(summary, f, ensure_ascii=False, indent=2)
        f.write("\n")

    print("Wrote unified index: %d records -> %s" % (len(rows), os.path.relpath(INDEX, ROOT)))
    for k, v in sorted(by_corpus.items()):
        print("  %-14s %d" % (k, v))


if __name__ == "__main__":
    main()
