#!/usr/bin/env python3
"""Generate numbers.tex for paper 3 from definition_analysis_results.json.

Retrofitted, and the retrofit paid for itself immediately: the manuscript said
the corpus holds 290 instruments, in five places, and the glossary it is
computed from holds 291. The figure had been carried over from a different
analysis --- one that counts instruments joinable to the judgment corpus,
which is a different set --- and no guard could see it, because there was no
guard. Every measurement in this article is now computed here and typeset from
a macro, as in papers 5, 7, 9 and 10.
"""

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
RESULTS = HERE / "definition_analysis_results.json"


def fmt(v):
    if isinstance(v, float):
        return f"{v:.2f}" if abs(v) < 10 else f"{v:.1f}"
    if isinstance(v, int):
        return f"{v:,}".replace(",", "{,}")
    return str(v)


def main():
    r = json.loads(RESULTS.read_text(encoding="utf-8"))
    c, k = r["corpus"], r["kind_split"]
    mi = r["multi_instrument"]
    dv = r["divergence_among_substantive"]
    ha = r["hand_adjudication_of_most_shared_substantive_terms"]
    cl = ha["classes"]

    N = {
        "nInstruments": c["instruments_total"],
        "nWithDefsArticle": c["instruments_with_a_definitions_article"],
        "nTerms": c["terms_total"],
        "nDefinitions": c["definition_occurrences_total"],

        "nIndexicalTerms": k["indexical_terms"],
        "nSubstantiveTerms": k["substantive_terms"],
        "nIndexicalDefs": k["indexical_definition_occurrences"],
        "nSubstantiveDefs": k["substantive_definition_occurrences"],

        "nShared": mi["terms_defined_by_more_than_one_instrument"],
        "nSharedIndexical": mi["of_which_indexical"],
        "nSharedSubstantive": mi["of_which_substantive"],

        "nCompared": dv["terms_compared"],
        "nIdentical": dv["identical"],
        "nNearIdentical": dv["near_identical"],
        "nDivergent": dv["divergent"],
        "nDivergentShare": 100 * dv["divergent_share"],
        # the similarity bands are chosen, not measured --- but they are chosen
        # in the analysis script, so the manuscript should not restate them
        "nThreshIdentical": dv["thresholds"]["identical"],
        "nThreshNear": dv["thresholds"]["near_identical"],

        # derived, but derived here rather than in prose
        "nSingleInstrument": c["terms_total"] -
                            mi["terms_defined_by_more_than_one_instrument"],
        "nSingleShare": 100 * (c["terms_total"] -
                               mi["terms_defined_by_more_than_one_instrument"])
                        / c["terms_total"],
        # the automatic filter's recall on the hand-read set: every class the
        # filter got right, over the twelve reviewed
        "nFilterCaught": ha["terms_reviewed"] - cl["indexical_missed"],
        "nFilterRecall": 100 * (ha["terms_reviewed"] - cl["indexical_missed"])
                         / ha["terms_reviewed"],

        "nReviewed": ha["terms_reviewed"],
        "nConflicting": cl["conflicting"],
        "nHarmonised": cl["harmonized"],
        "nInstrumentLocal": cl["instrument_local"],
        "nIndexicalMissed": cl["indexical_missed"],
        "nHomonymous": cl["homonymous"],
    }
    lines = ["% Generated by make_numbers.py from definition_analysis_results.json.",
             "% Do not edit: every value here has exactly one source, and it is",
             "% not this file. Regenerated before each build.", ""]
    for key, v in sorted(N.items()):
        lines.append(f"\\newcommand{{\\{key}}}{{{fmt(v)}}}")
    (HERE / "numbers.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote numbers.tex with {len(N)} values")
    for key, v in sorted(N.items()):
        print(f"  {key:<22}{fmt(v)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
