#!/usr/bin/env python3
"""Generate numbers.tex from the analysis outputs.

Every measurement in the manuscript comes from here. Nothing is typed into
the LaTeX; check_numbers.py refuses to build a manuscript that types one
anyway. The same discipline as the provenance and comparison papers, for the
same reason: a number typed once is a number that will disagree with its
source the first time the analysis is re-run.
"""

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC = HERE.parent / "arabic_paper"
sys.path.insert(0, str(SRC))

import match_instruments as M      # noqa: E402


def load(name):
    return json.loads((SRC / name).read_text(encoding="utf-8"))


def fmt(v):
    if isinstance(v, float):
        return f"{v:.1f}" if abs(v) >= 1 else f"{v:.3f}".lstrip("0")
    if isinstance(v, int) and abs(v) >= 10000:
        return f"{v:,}".replace(",", "{,}")
    return f"{v:,}".replace(",", "{,}") if isinstance(v, int) else str(v)


def main():
    inst = load("applied_law_v2_results.json")
    arts = load("applied_articles_results.json")
    voice = load("cite_by_voice_results.json")
    churn = load("churn_vs_litigation_results.json")

    named = sum(inst["named"].values())
    anaph = sum(inst["anaphoric"].values())
    matched = named + anaph
    cited_instruments = len(set(inst["named"]) | set(inst["anaphoric"]))

    PROC = M.PROCEDURAL
    combined = dict(inst["named"])
    for k, v in inst["anaphoric"].items():
        combined[k] = combined.get(k, 0) + v
    proc = sum(v for k, v in combined.items() if k in PROC)
    ranked = sorted(combined.values(), reverse=True)

    flat = sorted((c for a in arts["by_instrument"].values() for c in a.values()),
                  reverse=True)
    art_total = sum(flat)

    vp, vr = voice["counts"]["recital"], voice["counts"]["reasoning"]
    tp, tr = sum(vp.values()), sum(vr.values())
    pp = sum(v for k, v in vp.items() if k in PROC) / tp
    pr = sum(v for k, v in vr.items() if k in PROC) / tr
    att = voice["recital_attribution"]
    rp = voice["recital_procedural"]

    al = churn["article_level"]
    N = {
        "nJudgments": inst["judgments"],
        "nCitations": inst["citations"],
        "nNamed": named,
        "nAnaphoric": anaph,
        "nUnmatchedShare": 100 * (inst["citations"] - matched) / inst["citations"],
        "nInstruments": arts and 291,
        "nInstrumentsCited": cited_instruments,
        "nInstrumentsNever": 291 - cited_instruments,
        "nInstrumentsCitedShare": 100 * cited_instruments / 291,
        "nProceduralShare": 100 * proc / matched,
        "nTopOneShare": 100 * ranked[0] / matched,
        "nTopTenShare": 100 * sum(ranked[:10]) / matched,
        "nRegistryArticles": arts["registry_articles"],
        "nArticlesCited": arts["articles_cited"],
        "nArticlesCitedShare": 100 * arts["articles_cited"] / arts["registry_articles"],
        "nArtTopOneShare": 100 * flat[0] / art_total,
        "nArtTopTenShare": 100 * sum(flat[:10]) / art_total,
        "nArtTopHundredShare": 100 * sum(flat[:100]) / art_total,
        "nTopArticleCitations": flat[0],
        "nSegmented": voice["segmented"],
        "nSegmentedShare": 100 * voice["segmented"] / voice["judgments"],
        "nRecitalProcedural": 100 * pp,
        "nReasoningProcedural": 100 * pr,
        "nRecitalInstruments": len(vp),
        "nReasoningInstruments": len(vr),
        "nRecitalCitations": tp,
        "nReasoningCitations": tr,
        "nRecitalByCourt": att["court"],
        "nRecitalByCourtShare": 100 * att["court"] / (att["court"] + att["other"]),
        "nRecitalCourtProcedural":
            100 * rp["court_proc"] / (rp["court_proc"] + rp["court_other"]),
        "nRecitalOtherProcedural":
            100 * rp["other_proc"] / (rp["other_proc"] + rp["other_other"]),
        "nChurnSpearman": churn["instrument_level"]["spearman"],
        "nStatusArticles": al["articles"],
    }
    lines = ["% Generated by make_numbers.py from the analysis outputs.",
             "% Do not edit: every value here has exactly one source, and it is",
             "% not this file. Regenerated before each build.", ""]
    for k, v in sorted(N.items()):
        lines.append(f"\\newcommand{{\\{k}}}{{{fmt(v)}}}")
    (HERE / "numbers.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote numbers.tex with {len(N)} values")
    for k, v in sorted(N.items()):
        print(f"  {k:<26} {fmt(v)}")


if __name__ == "__main__":
    main()
